### ISSUE TITLE
Babel support

### ISSUE THREAD

**Issue by OleLaursen** [SmileyChris/django-countries#101]
Have you considered using Python Babel

http://babel.pocoo.org/

for the translation? It uses a set of shared data files with locale information and localised country and language names (CLDR):

http://cldr.unicode.org/

**Comment by OleLaursen** [comment]
Just in case you're interested in this at some point, here's some of the code I ended up with, I'm not using django-countries at the moment and it's a bit more primitive than what you have currently (I only need the language names), but perhaps still interesting:

```python
def babel_locale_from_django():
    lang = django.utils.translation.get_language()
    return babel.Locale.parse(django.utils.translation.to_locale(lang))

def country_code_name_list():
    """Returns list of tuples with country code and localised name. The list is sorted by name."""
    locale = babel_locale_from_django()

    choices = []
    for code in locale.territories:
        if code in ('ZZ', 'EU') or code.isdigit(): # regions
            continue

        choices.append((code, locale.territories[code]))
    choices.sort(key=lambda t: t[1])

    return choices

def country_name_from_code(country_code):
    return babel_locale_from_django().territories[country_code.upper()]

class CountryList(object):
    def __init__(self, only=None):
        self.only = None

    def __iter__(self):
        for code, name in country_code_name_list():
            if self.only and code not in self.only:
                continue

            yield code, name

all_countries = CountryList()
```

Then I integrated all_countries and country_name_from_code into the lazy country stuff from django-countries. Would be easier if Django supported generated choices. :)

**Comment by SmileyChris** [comment]
I guess it could be cool to have as an optional feature. It'd need some thinking about how it works with the django-countries options (like excluding / limiting countries).
It isn't something I can focus on right now, but if someone feels inclined, I'll review and merge when ready.

**Comment by SmileyChris** [comment]
I'm going to close this for now, if anyone reading it feels motivated to work on this, they can open a new issue or ping me to reopen this one.
