### ISSUE TITLE
Consistency of official ISO names

### ISSUE THREAD

**Issue by synotna** [SmileyChris/django-countries#103]
The usage of () in official ISO names is inconsistent

>>> dict(countries)['VE']
'Venezuela, Bolivarian Republic of'
>>> dict(countries)['TW']
'Taiwan (Province of China)'

Would a pull fixing them to be consistent (without ()) matching official ISO names be accepted?

**Comment by SmileyChris** [comment]
The names are pulled directly from the official iso list. I've considered
standardising them, but then it's breaking the actual standard. And it
would mean having to fix all the translations...

**Comment by SmileyChris** [comment]
Thanks for pointing this out! It looks like my code that was pulling this list in was broken.

**Comment by synotna** [comment]
Awesome :) I just noticed I was wrong about "without ()": I falsely assumed that the WIkipedia ISO pages would match what ISO themselves published!

Very small detail but can be a minor annoyance!

**Comment by SmileyChris** [comment]
Thank you for pointing this out though, I wouldn't have found the related bug without you :)
