### ISSUE TITLE
Add version info to __init__.py

### ISSUE THREAD

**Issue by evgenyfadeev** [SmileyChris/django-countries#105]
Maybe add a ``__version__`` variable?
It is sometimes useful to be able to determine version of the package with python code.

**Comment by SmileyChris** [comment]
Eh, I *guess*... I always forget to update these manual things though :P

Maybe I can just suggest people do this?
```python
import pkg_resources
pkg_resources.require('django-countries')[0].version
```

**Comment by evgenyfadeev** [comment]
thanks for the suggestion, maybe an option.

**Comment by SmileyChris** [comment]
Going to close this for now, it's not high priority.
