### ISSUE TITLE
Field is not serializeable with Django Rest Framework

### ISSUE THREAD

**Issue by vladlep** [SmileyChris/django-countries#106]
Hello,

I have encountered an issues when working with the country field and Django Rest Framwork.
If in the models we have a field that can be set to blank:

    country = CountryField(_('country'), blank=True, null=True, default='NL')

when used as a normal field in the serializer I get an error that: TypeError: Country(code=u'') is not 
JSON serializable. This happens only when the country field is blank. 

It has been reported by someone else also on the django rest framework group.
https://groups.google.com/forum/#!topic/django-rest-framework/3hrS2xr6BS0

I am not sure exactly if this can be solved on the django rest framework side but thought to report it here also. It might be solved on the django-countries side.

Thanks,
Vlad

**Comment by SmileyChris** [comment]
From my skim of the rest framework source, I would have thought that the `ModelSerializer` would have used a `rest_framework.fields.CharField` to represent the `CountryField`.
`CharField.to_representation` uses `six.text_type`, which would be run against the `Country` object, returning the code.

Where's this falling over?

If we do need to add a rest framework field in the django-countries source though, I'm cool with that too.

**Comment by vladlep** [comment]
I think the country field is translated into a serializers.ChoiceField. It works well if i have a country, but if it is not then it gets the error. 

How is solved it for my case:  I have a CompanySerializer and i overwrote the country field with a custom serializer. The default one would have been a serializers.ChoiceField:

    class SerializableCountryField(serializers.ChoiceField):
        def __init__(self, **kwargs):
            super(SerializableCountryField, self).__init__(choices=Countries())
    
        def to_representation(self, value):
            if value in ('', None):
                return '' # normally here it would return value. which is Country(u'') and not serialiable
            return super(SerializableCountryField, self).to_representation(value)

    class CustomerSerializerV2(serializers.ModelSerializer):
        country = SerializableCountryField(allow_blank=True)
    
        class Meta:
            model = Company
            fields = ('id', 'name', ''postal_code', 'address', 'city', 'country')

In the to_representaion method of the SerializableCountryField i returned and empty string instead of the normal  'value' variable. The value in that case is Countru(u'') which is not serializable.

I hope this helped?

**Comment by j0hnsmith** [comment]
@SmileyChris [`CharField.to_representation`](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/fields.py#L1045-L1048) only uses `six.text_type` when `value not in ('', None)`. 

    def to_representation(self, value):
        if value in ('', None):
            return value
        return self.choice_strings_to_values[six.text_type(value)]

`value` is in the tuple (due to `Country.__eq__`) so gets returned directly and [`rest_framework.utils.encoders.JSONEncoder`](https://github.com/tomchristie/django-rest-framework/blob/6add1acc4e5f701b99e9bf59bc7484fb9126ce49/rest_framework/utils/encoders.py#L16) doesn't know how to handle it.

Here's an alternative version of @vladlep's workaround

    class SerializableCountryField(serializers.ChoiceField):
        def to_representation(self, value):
            if value in ('', None):
                return ''  # instead of `value` as Country(u'') is not serializable
            return super(SerializableCountryField, self).to_representation(value)

    class CustomerSerializerV2(serializers.ModelSerializer):
        country = SerializableCountryField(allow_blank=True, choices=Countries())

        class Meta:
            model = Company
            fields = ('id', 'name', ''postal_code', 'address', 'city', 'country')

**Comment by SmileyChris** [comment]
Does this change fix it?

**Comment by j0hnsmith** [comment]
With that change [`return self.choice_strings_to_values[six.text_type(value)]`](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/fields.py#L1048) is run however it raises `KeyError` as the dict doesn't contain the key `u''` (the dict contains all the 2 char uppercase country codes).

**Comment by SmileyChris** [comment]
I'm guessing the code has changed in master from the version you're
running, since the line you listed says `choice_strings_to_values.get(...)`

**Comment by SmileyChris** [comment]
Yep, I see it was a change 7 days ago...

But isn't that correct - if you're allowing a blank value, wouldn't you need to add that blank "country" to the choices list?

**Comment by melinath** [comment]
FTR, my workaround - hackier, but less work:

```python
class MySerializer(serializers.ModelSerializer):
    # [...]
    def to_representation(self, obj):
        data = super(MySerializer, self).to_representation(obj)
        if data['country'] == '':
            data['country'] = ''
        return data
```

**Comment by murdav** [comment]
@SmileyChris do you know when Django countries will support Django Rest Framework >3 without adding code workaround?

Thanks a lot,

D

**Comment by Alp-Phone** [comment]
I don't have a fix for the problem, but here is how I serialize CountryField in DRF

```python
class DummySerializer(serializers.ModelSerializer):
    country_code = serializers.ReadOnlyField(source='country.code')
    country_name = serializers.SerializerMethodField()

    class Meta:
        model = Dummy
        fields = (
            'country_code',
            'country_name',
        )

    def get_country_name(self, obj):
        return force_text(obj.country.name)
```

**Comment by murdav** [comment]
Thanks for this.

D

**Comment by SmileyChris** [comment]
@murdav have you tried with DRF >= 3.1.3 and django-countries master?

If I get confirmation this works, I'll roll a new release.

**Comment by Alp-Phone** [comment]
You're welcome.
That's a read-only serializer.  I don't know how CountryField behaves in a write scenario.

**Comment by Alp-Phone** [comment]
@SmileyChris I just tried DRF 3.1.3 with django-countries@1102bbcf1a55b41123e508ebbde0321f8e4cdc5f and I get TypeError: Country(code=u'') is not JSON serializable when serialized an empty country field.

**Comment by FabioFleitas** [comment]
I also don't have a fix for the problem, but I wrote a slightly modified version of the serializer posted here to account for an edge case where the country code provided is not in `Countries()`
```python
from django.utils.encoding import force_text
from rest_framework import serializers
from django_countries import Countries

class CountryFieldSerializer(serializers.ChoiceField):
    def __init__(self, **kwargs):
        super(CountryFieldSerializer, self).__init__(choices=Countries())

    def to_representation(self, value):
        if value in ('', None):
            return force_text(value)
        return force_text(super(CountryFieldSerializer, self).to_representation(value))
```

The `TypeError` occurs when [`to_representation` returns `value`](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/fields.py#L1236), which it does in the case `value in ('', None)` and when `value` is not a valid choice from `Countries()`

**Comment by SmileyChris** [comment]
CountryField DRF serializer field added in 3.4

**Comment by rschwiebert** [comment]
So with django-countries 3.4.1, django 1.7, DRF 3.3.0, I get this:

TypeError: Country(code=None) is not JSON serializable

Shouldn't this be handled here?

**Comment by j0hnsmith** [comment]
Hello!

 

New message, please read <http://sweetchicory.com/arrived.php?cd0>

 

info@whywouldwe.com

**Comment by j0hnsmith** [comment]
Hello!

 

New message, please read <http://imsomemphis.us/living.php?xnl>

 

info@whywouldwe.com

**Comment by j0hnsmith** [comment]
Hello!

 

New message, please read <http://xerox.web.tr/stopped.php?bg>

 

info@whywouldwe.com

**Comment by a1Gupta** [comment]
+1 @SmileyChris

**Comment by SmileyChris** [comment]
I'm sure something can be done about this, sorry for leaving it closed so long.

Reopening and will take a look at it some time in the future if no-one else takes a crack at it first!

**Comment by carltongibson** [comment]
Just a data point: we're using the `CountryField` serialiser field without any issue...

**Comment by jgeerds** [comment]
@rschwiebert It works for me. Are you sure you're using the right serializer?

```
from django_countries.serializer_fields import CountryField

class FoobarSerializer(serializers.ModelSerializer):
    country = CountryField()

    class Meta:
        model = Foobar
        fields = ('country', )
```

**Comment by rschwiebert** [comment]
@jgeerds Since the suggestion above fixed the problem, I probably won't be looking back into this. Thanks

**Comment by madEng84** [comment]
@jgeerds thanks for it but it will be great if CountryField was a serializers.ChoiceField...

I change Country Field and now it seems to work good (but i didn't test it O_O)

```
from __future__ import unicode_literals

from rest_framework import serializers
from django.utils.encoding import force_text

from django_countries import countries
from django_countries import Countries

class CountryField(serializers.ChoiceField):

    def __init__(self, choices=Countries(), *args, **kwargs):
        self.country_dict = kwargs.pop('country_dict', None)
        countries_class = kwargs.pop('countries', None)
        self.countries = countries_class() if countries_class else countries
        choices = self.countries
        super(CountryField, self).__init__(choices, *args, **kwargs)

    def to_representation(self, obj):
        code = self.countries.alpha2(obj)
        if not code:
            return ''
        if not self.country_dict:
            return code
        return {'code': code, 'name': force_text(self.countries.name(obj))}

    def to_internal_value(self, data):
        if isinstance(data, dict):
            data = data.get('code')
        return self.countries.alpha2(data)
```

p.s. I don't know what is the difference between Countries() and self.countries but I took the second


Is it impossible for you to merge this to master and upload it on Pypy? 
Thank you in advance

**Comment by karina-klinkeviciute** [comment]
I used django_countries.serializer_fields and everything's fine with representing a field - whether it's empty or not and also everything's fine with saving it, also - with empty and non-empty fields. Yet what doesn't work as supposed - when a country code is being supplied, it doesn't get returned in a response, only an empty string is being returned:  `"country": ""`. It's not a big issue I guess, because the country code is being saved correctly and when viewed in the list, it is there. But I still found it worth mentioning.

**Comment by jeffjvick** [comment]
@SmileyChris I had the same issue as @rschwiebert did and @jgeerds suggestion helped.  

I was using:
`from django_countries.fields import CountryField`
When I should have been using:
`from django_countries.serializer_fields import CountryField`

I think it would be helpful to add the correct import statement needed in the the code section of "Django Rest Framework field" on the readme as it wasn't obvious since it's the same name as the Django field.

**Comment by SmileyChris** [comment]
Can someone from this thread please put together a quick documentation fix for the readme? I'll merge it and the other outstanding requests and push out a quick release.

**Comment by BigWhale** [comment]
I created a pull request with a tiny fix for the serializer that makes it a ChoiceField. This is useful when front end relies on OPTIONS to correctly render the user interface and populates all the country selectors with the list that was sent by the backend.

Can this be merged into master?

**Comment by Noaiii** [comment]
@vladlep Thank you!

**Comment by professorhaseeb** [comment]
this error come in multi-select countries. to fix it just add `CountryFieldMixin` in the serializer
eg: `class MySerializer(CountryFieldMixin, serializers.ModelSerializer)`

**Comment by Woodman5** [comment]
Hello!

I found that this `from django_countries.serializer_fields import CountryField` doesn't work with `CountryField(multiple=True)` because "to_representation" method doesn't work with lists.
So I wrote my own class:
```
class MultiCountry(CountryField):
    def to_representation(self, obj):
        countries = []
        for item in obj:
            code = self.countries.alpha2(item)
            if not code:
                countries.append({"code": ""})
            if not self.country_dict:
                countries.append({"code": code})
            if self.country_dict:
                countries.append({"code": code, "name": force_str(self.countries.name(item))})
        return countries
```
Am I right or misunderstood somethign?

**Comment by kunambi** [comment]
>             if not self.country_dict:
>                 countries.append({"code": code})

I think it looks correct, however you should replace these two lines in order to have a consequential behaviour:

>             if not self.country_dict:
>                 countries.append(code)
