### ISSUE TITLE
Possible Adding of Countries

### ISSUE THREAD

**Issue by tzenderman** [SmileyChris/django-countries#107]
Hey @SmileyChris, first: thanks for a great project!

I'm trying to see how I can add Kosovo to the list of countries, and I've already seen the past discussion on this here (https://github.com/SmileyChris/django-countries/issues/16). Any way we could add a method to use in our project's settings that will add a country to the list in data? Something similar to this: https://github.com/limist/py-moneyed/blob/master/src/moneyed/classes.py#L191-L198

Let me know and I should be able to write up a small PR for this.

**Comment by SmileyChris** [comment]
Just add this in your settings (as the readme explains)
```python
_ = lambda s: s

COUNTRIES_OVERRIDE = {'KV', _('Kosovo')}
```

**Comment by tzenderman** [comment]
Ah, sorry about that - didn't realize I could also append new countries. Thanks!

**Comment by SmileyChris** [comment]
No worries. If you have any suggestions for making that clearer, feel free
to pull request 😉

**Comment by nuschk** [comment]
For those of us, just copy&pasting this, it actually has to read:

```python
COUNTRIES_OVERRIDE = {'XK': _('Kosovo')}
```

(You don't want to pass a set... Wasted a few minutes until I figured that out.) 😄
