### ISSUE TITLE
It would be nice to have a template filter to print the full country name for the provided code

### ISSUE THREAD

**Issue by loop0** [SmileyChris/django-countries#109]
Something like this would be very nice to have at hand:

```django
{{ country_code|countryname }}
```

```python
@register.filter
def countryname(value):
    return countries.name(value) or value
```

I can make a pull request if you approve to include it!

**Comment by SmileyChris** [comment]
Usually the country cod just comes from a CountryField, but I guess
supporting 3rd party or external sources is a valiant goal. Maybe the
filter should return a Country object?

**Comment by loop0** [comment]
Returning a country object is an even better idea! I just thought about full country name because it was the use case for me.

**Comment by SmileyChris** [comment]
If you're keen, a PR would be good. Tests appreciated if you want to go the whole hog ;)

**Comment by SmileyChris** [comment]
I'm closing now, but if anyone feels motivated, reopen with a pull request.
