### ISSUE TITLE
Documenting Creating a Country Form Field

### ISSUE THREAD

**Issue by michaeljones** [SmileyChris/django-countries#111]
Hi,

Using and loving this app. Thanks for writing it.

I've got a form in which I needed the `country` field to optional but it was tied to a non-optional field on the Model. So I wanted to create a field on the form to override it. I ended up with:

```
from django_countries import countries
country = forms.ChoiceField(choices=countries, required=False)
```

Which I realise is not hard but in my current state of not knowing this app or perhaps Django as well as I should do I've spent a rather long time figuring it out. Would you might if I tried a pull request to adding this detail into the README so that it is there for future people like me?

Thanks again,
Michael

**Comment by SmileyChris** [comment]
Definitely worth documenting it because this isn't actually correct :-1: 

If you're using a form field, you want to ensure the translatable strings for the country choices are left lazy until the widget renders, so you need to do this:

```
country = django_countries.fields.LazyTypedChoiceField(choices=countries, required=False)
```

**Comment by michaeljones** [comment]
That's great. Thanks for that!
