### ISSUE TITLE
[newbie question] using .flag

### ISSUE THREAD

**Issue by amitbend** [SmileyChris/django-countries#118]
Hi,
I just install the app and I created a "country = CountryField()"
on the html i added this "{{item.country.flag}}"
but instead of a flag i see this "/static/flags/af.gif"
what's the right way to show the flag?

**Comment by lhuriguen** [comment]
You have to use an img tag in your HTML:
```html
<img src="{{ item.country.flag }}" title="{{ item.country.name }}">
```

**Comment by amitbend** [comment]
thanks!
