### ISSUE TITLE
Relation fields do not support nested lookups

### ISSUE THREAD

**Issue by alexkasina** [SmileyChris/django-countries#120]
Installed the app and trying to search user by country like `MyModel.objects.filter(user__userprofile__country_name__icontains="australia")`  and am getting a `FieldError` `Relation fields do not support nested lookups` Seems `name` in this case isn't a field. How can I achieve the search?

 `  # models.py`
    `class MyModel(models.Model):`
       ` country = CountryField(blank=True)`

**Comment by SmileyChris** [comment]
You can't. `.filter` is for filtering at the database level. The name only exists in Python (and you're not thinking very internationally, as the name is a translated string so this would have a different result depending on the active locale).

**Comment by jplehmann** [comment]
Hi Chris, I'm trying to achieve the same thing.  What surprises me is that I have one field which is a singular country, and I am able to filter on this one. The `contains` treats the field like a string and works at the database level.

However, with another field which is a multi, it does not treat it as a string and we get the "not supported" error. If I could search it as a string this would at least be a sort of workaround.  Can you say why that is not possible or with an alternative recommendation?

Thanks for the help, I realize this is not a bug but more of a feature request.

**Comment by jplehmann** [comment]
Nevermind!  

* I didn't read the original closely enough and now I see they were trying to filter on `name` which is not what I was trying.
* The reason I was getting the same error was that I mistyped the field name. Now, filtering on multi-field works as desired. (e.g, `.filter(store__multi_country__contains=',NL,')`).
