### ISSUE TITLE
XSS vulnerability

### ISSUE THREAD

**Issue by pawelkrupinski** [SmileyChris/django-countries#121]
Our penetration testers found an XSS vulnerability which I was able to trace back to django-countries (version 3.3).

If you post this value of the country (no html escaping necessary):
```
PLsnm'"></textarea><h1>XSS2<script>alert(document.domain)</script>
```
The country flag image will be rendered like this (an error message with the value will be displayed as well, but it's html-escaped):
```
<img class="country-select-flag" id="flag_id_country"
style="margin: 6px 4px 0"
src="/static/flags/plsnm'"></textarea><h1>xss2<script>alert(document.domain)</script>.gif">
```
Allowing the code to be executed.

It might make sense not to render the flag if the country code is invalid.

**Comment by SmileyChris** [comment]
This was fixed on master, I just haven't rolled a release in far too long. Done now as 3.4
