### ISSUE TITLE
Line #55 in locale/ja/LC_MESSAGES/django.po is untranslated

### ISSUE THREAD

**Issue by almond55** [SmileyChris/django-countries#124]
https://github.com/SmileyChris/django-countries/blob/master/django_countries/locale/ja/LC_MESSAGES/django.po#L55

This is missing the ja translation, which is supposed to be モルドバ.

Incidentally, is it a duplicate of line 665-667?

**Comment by SmileyChris** [comment]
Please update this here https://www.transifex.com/smileychris/dashboard/all_resources/ja/?project=django-countries

Thanks!
