### ISSUE TITLE
Sprite to reduce the amount of downloaded files

### ISSUE THREAD

**Issue by NotSqrt** [SmileyChris/django-countries#128]
Hello,

Using [Glue](http://glue.readthedocs.org/en/latest/index.html), I was able to build the following sprite with the corresponding css.

(as simple as `glue django_countries/static/flags/ destination_folder`)

![flags](https://cloud.githubusercontent.com/assets/1997005/12489847/b8d88a56-c072-11e5-8066-87bc45d1d680.png)

Is there a way to build this into a usable template tag, for instance, with another tag that loads the appropriate css file ?

**Comment by SmileyChris** [comment]
This sounds like a good idea, maybe with a new `Country` method which returns the correct css classes for the country. Wouldn't need a tag for the other css file, just add it to docs that to use that method you need to reference the new static flags countries-sprite.css file.

**Comment by SmileyChris** [comment]
... and just released v4.2 with this code in it :)
