### ISSUE TITLE
How to use default set of countries after COUNTRIES_OVERRIDE ?

### ISSUE THREAD

**Issue by a1Gupta** [SmileyChris/django-countries#129]
I want to create two types of CountryField one for user's country for which i am using default countries list and other CountryField in which I want to add some more choices. But how to use both types of fields together. One field for standaed countries and other for countries with COUNTRIES_OVERRIDE option.

**Comment by SmileyChris** [comment]
`CountryField` accepts a `countries` keyword argument that can contain a custom countries object. That class should look something like:
```python
class CustomCountries(Countries):
    override = ...
```
