### ISSUE TITLE
get the full name issue

### ISSUE THREAD

**Issue by karimone** [SmileyChris/django-countries#130]
Check the following code. Is it a bug? (version 3.4.1)

```
In [18]: ll.country
Out[18]: Country(code=u'AU')

In [19]: ll.country.name
Out[19]: <django.utils.functional.__proxy__ at 0xb60be82c>

In [20]: ll.country.code
Out[20]: u'AU'
```

**Comment by SmileyChris** [comment]
It's the expected behaviour.

Use `force_text` as found here to convert the lazy translatable string into an actual string (or just use `'%s' % ll.country.name`, assuming Python 3 or the use of `from __future__ import unicode_literals`)
