### ISSUE TITLE
Adding country field in admin list_display causes performance issues

### ISSUE THREAD

**Issue by sephii** [SmileyChris/django-countries#131]
Not sure it's really a bug but I think it should at least be documented somewhere. If you add a country field in `ModelAdmin.list_display`, you'll end up with a performance degradation of about 500ms. That's because of [the way Django displays the fields](https://github.com/django/django/blob/1.9.2/django/contrib/admin/utils.py#L387), which rebuilds a `dict` out of all the country choices for every object, which is quite time consuming.

An easy way to solve this manually is by defining a custom model method which takes care of doing the lookup in Django countries.

**Comment by SmileyChris** [comment]
I agree that this doesn't need a code change, but a documentation note of "don't do this" would be nice. If someone wants to write the docs and pull request, I'll add it in.
