### ISSUE TITLE
Missing some "countries"

### ISSUE THREAD

**Issue by batiste** [SmileyChris/django-countries#139]
Hi,

Today I was mapping a list of countries with django_countries and I find out those seems to be missing in your database

Kosovo
Palestinian territories
Netherlands Antilles
Tibet
Vatican City State (Holy See)

Not sure those have an official 2 letter code yet. But maybe it is worth checking.

**Comment by SmileyChris** [comment]
Check against iso3166, that's the country list that django-countries implements. You can always extend / modify this with your own choices of countries with the provided settings.
