### ISSUE TITLE
`Country` descriptor does not work with `defer()` and `only()`

### ISSUE THREAD

**Issue by spookylukey** [SmileyChris/django-countries#148]
See PR #147 

I don't know if there is an easy fix or not!

**Comment by SmileyChris** [comment]
Note to self, this is only in Django 1.10...

**Comment by SmileyChris** [comment]
And @spookylukey , `.only()` seems fine. Just the `.defer()` is failing for me

**Comment by SmileyChris** [comment]
Only wasn't fine, you just hadn't added any explicit tests for those (since it's the same mechanics anyway)

**Comment by SmileyChris** [comment]
Fixed in 5bf6e9a
