### ISSUE TITLE
CountryField validation in Model and Serializer

### ISSUE THREAD

**Issue by muhammad-ammar** [SmileyChris/django-countries#150]
What is correct way to perform validation on CountryField in Model and DRF Serializer? `validate_country` doesn't work because empty string is received in the method in case of invalid country value. 

``` Python
class ProfileSerializer(serializers.ModelSerializer):
    country = CountryField()

    class Meta:
        model = UserProfile
        fields = ('language', 'country', 'timezone', 'latitude', 'longitude')

    def validate_country(self, country):
        ...
```

**Comment by SmileyChris** [comment]
You probable weren't importing the serializer field: https://github.com/SmileyChris/django-countries#django-rest-framework-field

**Comment by hugorodgerbrown** [comment]
@SmileyChris I've just come across a similar (related?) issue - using the serializer I can populate the data with an invalid country and it passes validation. Am I doing something wrong?

```python
def test_invalid_country(self):
    """Check that invalid country codes are picked up."""
    data = {
        'city': 'London',
        'postcode': 'SE1',
        'country': 'foobar'
    }
    serializer = MyAddressSerializer(data=data)
    self.assertFalse(serializer.is_valid())
```

**Comment by hugorodgerbrown** [comment]
Looking at this - this is the expected behaviour - https://github.com/SmileyChris/django-countries/blob/master/django_countries/serializer_fields.py#L18
