### ISSUE TITLE
multiple=True raises a TypeError: __init__() got an unexpected keyword argument 'multiple'

### ISSUE THREAD

**Issue by helio-correia** [SmileyChris/django-countries#154]
Hi, i'm trying this package and when I try to use the multiple=True it raises the following error on migration: 
`TypeError: __init__() got an unexpected keyword argument 'multiple'`

Without the multiple it works as expected.

I'm using python3, django 1.9.10 and django-countries 4.0

My code
```
from django_countries.fields import CountryField

class Player(models.Model):
    name = models.CharField(_("name"), max_length=200)
    countries = CountryField(multiple=True)
```

I'm I doing something wrong?

**Comment by SmileyChris** [comment]
`multiple=True` is staged for the next release (very soon). You can `pip install -e https://github.com/SmileyChris/django-countries.git` to try it out

**Comment by helio-correia** [comment]
Thanks for reply, with the master the error goes away but it fails on the admin.

And I notice that on the migration it creates the field like this

```
migrations.AddField(
            model_name='player',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, default='', max_length=2, verbose_name='nationality'),
        ),
```

and i should be more right?

I'll wait for the next release and when I get some time i'll give a look in to it
