### ISSUE TITLE
Multiple countries doesn't work in forms or admin

### ISSUE THREAD

**Issue by knyghty** [SmileyChris/django-countries#156]
```
class Foo(models.Model):
    countries = CountryField(multiple=True)
```

Doesn't work in admin or any forms I tried, gives an error such as:

`Select a valid choice. ['AF', 'DZ'] is not one of the available choices.`

**Comment by mr-linch** [comment]
+1

**Comment by wimfeijen** [comment]
This does not work for me either. 

I am sorry I am unable to find a solution and create a pull request.

**Comment by jplehmann** [comment]
I also saw this in the docs and tried to use it.  I then realized it wasn't yet in a released version, and saw tests have been failing since this time, which doesn't give me a warm fuzzy.

![image](https://cloud.githubusercontent.com/assets/460964/22853864/59717ad4-f026-11e6-9eb9-6a5ae7d0c2e7.png)

**Comment by jplehmann** [comment]
I get the same error. When trying to save the form, validation fails.  Would be great to have this working @SmileyChris .   Or maybe at least a disclaimer in the README.
