### ISSUE TITLE
Country choices not enforced on save()

### ISSUE THREAD

**Issue by wetneb** [SmileyChris/django-countries#157]
It is possible to save a Country field with an incorrect code in it. I would have expected the country to be checked against the list of countries provided.

```
class institution(Model):
    country = CountryField()

i = Institution()
i.country = 'XX'
i.save() # Should raise an exception
```

**Comment by SmileyChris** [comment]
That's the correct behaviour.

If you want to validate it yourself, use `i.full_clean()`.
If you're using a modelform, it will do this.
