### ISSUE TITLE
Translating countries in Django model

### ISSUE THREAD

**Issue by dheavy** [SmileyChris/django-countries#158]
First off, thanks for the great work on this lib. It's a fantastic time-saver, and a really well-done one.

My issue is a bit of a noob's one. 
I have a model that must be of a certain type (i.e. it cannot be a LazyTypedChoiceField).
It will be rendered as a form element in my application.
I'm unpacking django_countries.fields to seed its choices (snippet below).

```python
from django.utils.translation import ugettext_lazy as _

country_select = models.CharField(
    verbose_name=_(u'In which country were you born?'),
    widget=widgets.Select(),
    choices=tuple((code, _(name)) for code, name in list(countries))  # notice the call to `_()` on name
)
```

It works fine, except for the localization. Calling ugettext_lazy within the comprehension doesn't work. The list of countries in my widget seemingly never get localized and remain in English.

I'm not sure how to proceed... I hate to be *that* guy (y'know, that one guy who fills an issue on Github when it might have nothing to do with you lib, and more with my ignorance of Python), but hey... I figured you could point me to the right direction. 😅 

Thanks in advance!

**Comment by PaulSD** [comment]
This seems to work for me... Maybe try something like this to debug:
from django.utils.functional import lazy
def test_trans(orig_str):
  print "translating "+orig_str
  translated = ugettext(orig_str)
  print "translated to "+translated
  return translated
...
choices=tuple((code, lazy(test_trans, str)(name)) for code, name in list(countries))

This will tell you when the translation is happening - maybe it's happening at import time rather than run time for some reason?

**Comment by dheavy** [comment]
Hi @PaulSD , just wanted to say thanks for the input, I'll be able to give it a look after the holidays!

**Comment by dheavy** [comment]
Hi again @PaulSD,

Following your advice I tried the following (in Python 3):
```python
def test_trans(orig_str):
    print('get_language', get_language())
    print("translating " + orig_str)
    translated = _(orig_str)
    print("translated to " + str(translated))
    return translated

test_trans(countries[51][1])
```

Which printed out: 
```bash
get_language fr
translating Congo (the Democratic Republic of the)
translated to Congo (the Democratic Republic of the)
``` 

I was expecting the third to be translated to `Congo (République Démocratique du)`, or something like that.

The rest of the application is properly translated though.

I'm such a noob at how i18n works in Django, I don't really know where to look for answers. If you have any ideas, I'll be in your debt...

**Comment by SmileyChris** [comment]
Just a thought, are you sure you've got django_countries in your
INSTALLED_APPS?

**Comment by dheavy** [comment]
**Thank you!**

I completely overlooked it. That was the issue!
Closing it and thanking you a million times!
