### ISSUE TITLE
Crashes with Django 1.11

### ISSUE THREAD

**Issue by askoretskiy** [SmileyChris/django-countries#164]
In Django 1.11 they removed BaseSettings class. That makes django-countries crash:

    File "/usr/local/lib/python3.6/site-packages/django_countries/__init__.py", line 5, in <module>
        from django_countries.conf import settings
      File "/usr/local/lib/python3.6/site-packages/django_countries/conf.py", line 4, in <module>
        class AppSettings(django.conf.BaseSettings):
    AttributeError: module 'django.conf' has no attribute 'BaseSettings'

Bad thing is that it is crashing even when trying to use countries list.

In Django 1.11 they have Settings and UserSettingsHolder but I cannot tell you how to fix it. See https://github.com/django/django/blob/1.11a1/django/conf/__init__.py

**Comment by askoretskiy** [comment]
While it is not fixed, you could use https://pypi.python.org/pypi/pycountry

**Comment by SmileyChris** [comment]
Fixed, and new version released

**Comment by askoretskiy** [comment]
@SmileyChris Thank you!
