### ISSUE TITLE
Adding latitude and longitude to countries

### ISSUE THREAD

**Issue by mvantellingen** [SmileyChris/django-countries#165]
Hey, thanks for this library! 

I was wondering if you are interested in a PR which implements latitude/longitude attributes on the countries based on the data from https://developers.google.com/public-data/docs/canonical/countries_csv

**Comment by SmileyChris** [comment]
Glad to be of service. I'm not sure if adding the lat/long would be really necessary to tie to the project - it could be a separate app that provided this data. If you want to develop it, I'd be fine with adding a method to the `Country` which assumed your app was installed and returned the relevant data for its country code.

**Comment by mgrsantox** [comment]
@mvantellingen is right . It could be amazing having latitude and longitude attributes while making GIS application. So that we don't need Google geocoding API to get lat/long by passing country name.
