### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by Borkason** [SmileyChris/django-countries#169]
I am building a web site in non-english. I don't plan to translate anything into another language, so I didn't implement i18n or l10n. The countries are shown in english. What is the easiest and fastest way to show the countries on my form in my language?

```django
<select id="{{ form.land.id_for_label }}" class="form-control" aria-describedby="{{ form.land.id_for_label }}Help">
  {% for key,val in form.land.field.choices %}
    <option value="{{ key }}">{{ val }}</option> <!-- `val` must be shown in my language, not in English -->
  {% endfor %}
</select>
{% if form.land.help_text %}<small id="{{ form.land.id_for_label }}Help" class="form-text text-muted">{{ form.land.help_text }}</small>{% endif %}
```

**Comment by SmileyChris** [comment]
In settings:
1. `LANGUAGE_CODE = 'de'`
2. ensure `'django_countries'` is in `INSTALLED_APPS`
3. check you *haven't* set `USE_I18N = False`

**Comment by Borkason** [comment]
It does not work, country names are still in English.

```python
LANGUAGE_CODE = 'de'
TIME_ZONE = 'Europe/Berlin'
USE_I18N = True
USE_L10N = True
USE_TZ = True
```

**Comment by Borkason** [comment]
Ugh, I forgot to add ' django_countries' to installed apps. Weird that it did work with English names, though. That's why I didn't even look there.
