### ISSUE TITLE
error importing CountryField

### ISSUE THREAD

**Issue by dblado** [SmileyChris/django-countries#173]
Using Django 1.9.6. I'm getting the following error trying to use CountryField:

django.core.exceptions.AppRegistryNotReady: The translation infrastructure cannot be initialized before the apps registry is ready. Check that you don't make non-lazy gettext calls at import time.

I went through the normal Google searching to make sure I was using:
```
from django.core.wsgi import get_wsgi_application
application = get_wsgi_application()
```

I found that editing:
https://github.com/SmileyChris/django-countries/blob/master/django_countries/filters.py#L3

from:
```
from django.utils.translation import ugettext as _
```
to:
```
from django.utils.translation import ugettext_lazy as _
```
fixed my issue but not sure if it's the right fix. Looking for some guidance so I can use this package.

**Comment by SmileyChris** [comment]
And released as 4.3. Thanks :)
