### ISSUE TITLE
How to add '--------' on select option when using CustomForm

### ISSUE THREAD

**Issue by gyugyu90** [SmileyChris/django-countries#177]
I am using LazyTypedChoiceField in a form. I want to set blank label ('--------') at the very top of the select, but I cannot figure out how. Currently, I am using the following code as a walkaround.
````
from django import forms
from django_countries import countries
from django_countries.fields import LazyTypedChoiceField

class StoreWizardForm1(forms.Form):
    nation = LazyTypedChoiceField(choices=[('','---------')]+list(countries), widget = LazySelect(attrs={'id':'nation-select'}))
   ...
````

but this cannot provide translated country names...
If I just use `choices=countries`, it doesn't show '---------' thing. I am not using a ModelForm because it is in the FormWizard

Can somebody help me out?

**Comment by SmileyChris** [comment]
So you want choices to be a lazy object but include the empty choice, and luckly this is already done on the `CountryField.get_choices` method for you (it has an `include_blank` argument that already defaults to `True`):

```python
from django import forms
from django_countries import countries
from django_countries.fields import LazyTypedChoiceField, CountryField

class StoreWizardForm1(forms.Form):
    nation = LazyTypedChoiceField(choices=CountryField().get_choices(), widget=LazySelect(attrs={'id':'nation-select'}))
   ...
```
