### ISSUE TITLE
CountryField raises AttributeError on model creation with Django 1.11

### ISSUE THREAD

**Issue by aktiur** [SmileyChris/django-countries#178]
I was trying Django 1.11 and noticed the following problem. When trying to create a new instance of a model, django_countries raises the following exception:

```
AttributeError at /people/

The 'location_country' attribute can only be accessed from Person instances.
```

I was able to retrace what's happening by comparing django 1.10.7 and Django 1.11.

The responsible modification is in django.db.models.base, in the `__init__` method of class `Model`, at the very end:

```
            # THE EXCEPTION IS RAISED ON THE LINE BELOW
            property_names = opts._property_names
            for prop in tuple(kwargs):
                try:
                    # Any remaining kwargs must correspond to properties or
                    # virtual fields.
                    if prop in property_names or opts.get_field(prop):
                        if kwargs[prop] is not _DEFERRED:
                            _setattr(self, prop, kwargs[prop])
                        del kwargs[prop]
                except (AttributeError, FieldDoesNotExist):
                    pass
```

`_property_names` is a simple of property of the `_meta` object that basically collects all properties from the model by getting, all attributes, and checking if they are instance of `property`:

```
        return frozenset({
            attr for attr in
            dir(self.model) if isinstance(getattr(self.model, attr), property)
})
```

which raises the final exception, when invoking `getattr(self.mode, attr)` with `attr` set to the name of a `CountryField`.

In Django 1.10.7, the problem was not happening as Django was not trying to find all properties, but only those of keys remaining in `kwargs`.

```
            for prop in list(kwargs):
                try:
                    # Any remaining kwargs must correspond to properties or
                    # virtual fields.
                    if (isinstance(getattr(self.__class__, prop), property) or
                            self._meta.get_field(prop)):
                        if kwargs[prop] is not DEFERRED:
                            setattr(self, prop, kwargs[prop])
                        del kwargs[prop]
                except (AttributeError, FieldDoesNotExist):
                    pass
```

As I do not know why this restriction of the field only being accessible from actual instances is enforced, I don't really know how to proceed from there: if you have any pointer, I don't mind making a pull request.

**Comment by SmileyChris** [comment]
Hrm, I just updated the tests to run against Django 1.11 too and there were no failures. Do you think you could put together a test case showing the problem?

**Comment by aktiur** [comment]
I just made a pull request with a new test case : #179

**Comment by aktiur** [comment]
Great! Thank you very much for the fast release!
