### ISSUE TITLE
Renders awfully slow with Django 1.11 and DEBUG=True

### ISSUE THREAD

**Issue by karolyi** [SmileyChris/django-countries#183]
Hey,

I'm using this field in my project, and since I changed to Django 1.11, the field takes **2-3 minutes** to render. In Django 1.11, they have introduced [the template based widget rendering](https://docs.djangoproject.com/en/1.11/releases/1.11/#template-based-widget-rendering), which changed quite a lot of code. I tried to dive into it through countryfield's initialization, but after 7-8 levels of code stack and spending ~4hrs on it, I gave up.

Could you guys please look into it? It's pretty much a pain in the ass to develop this way.

The automated tests will not show this error, as they use `DEBUG=False`.

Cheers

**Comment by SmileyChris** [comment]
Someone else noted that the problem for them was django debug toolbar. Are
you using this, and of so, doors disabling that entirely help?

**Comment by karolyi** [comment]
yes, turning off debug toolbar (& debug panel which I use) seems to speed the rendering up.

is there a way to fix this problem? I'd like to keep using those in  development, they are a help.

**Comment by ikcam** [comment]
Just disable `Templates`

```python
# Django Debug Toolbar
# Fix: Conflict between django-countries and django-debug-toolbar
DEBUG_TOOLBAR_CONFIG = {
    # Add in this line to disable the panel
    'DISABLE_PANELS': {
        'debug_toolbar.panels.templates.TemplatesPanel',
        'debug_toolbar.panels.redirects.RedirectsPanel',
    },
}
```

**Comment by karolyi** [comment]
I can live with that. The panel I use most is the SQL one.

**Comment by ppython** [comment]
Just to update people stumbling onto this thread:
It has been fixed with https://github.com/jazzband/django-debug-toolbar/commit/bb9bce5985af589f653ed4aa2e9c632f03eb6445 
The issue page in django-debug-toolbar:  https://github.com/jazzband/django-debug-toolbar/issues/910
