### ISSUE TITLE
andorra flag is broken and causes selected choices after to not show any flag at all

### ISSUE THREAD

**Issue by cjdcordeiro** [SmileyChris/django-countries#184]
to replicate, select andorra from the widget, the flag won't appear, but then for all other countries, no flags will appear as well

**Comment by SmileyChris** [comment]
`ad.gif` is getting blocked by adblock. Try turning that off.

**Comment by ViktorovEugene** [comment]
here is a workaround:
1. make a copy of the `flags/ad.gif` in your `static` with the name `flags/andora.gif`
2. make a monkey patch  from one of your applications `your_app/apps.py`:

       from django.apps import AppConfig
       class YourAppConfig(AppConfig):
           name = 'your_app'
           def ready(self):
                from django_countries import widgets
                widgets.COUNTRY_CHANGE_HANDLER = \
                    "var e=document.getElementById('flag_' + this.id); " \
                    "if (e) e.src = '%s'.replace('{code}'," \
                    " this.value.toLowerCase() === " \
                    "'ad' ? 'andora' : this.value.toLowerCase() || '__')" \
                    ".replace('{code_upper}', this.value.toUpperCase() || '__');"

3. Be sure to plugins this application in `INSTALLED_APPS` as `your_app.apps.YourAppConfig`

**Comment by SmileyChris** [comment]
My guess is that this unlock or another ad blocker knocking it out. Makes
sense to work around though I guess.
