### ISSUE TITLE
Very inefficient pickle/cache behaviour

### ISSUE THREAD

**Issue by craigds** [SmileyChris/django-countries#187]
Before [this commit](https://github.com/SmileyChris/django-countries/commit/cd08c4b94f8ee5f257c97479ccac43f4477c500d), caching a Country was relatively efficient:

```python
In [5]: len(pickle.dumps(user.country))
Out[5]: 187
```

After that commit, the size of the pickle exploded:

```python
In [5]: len(pickle.dumps(user.country))
Out[5]: 17365
```

Because pickle traverses the CountryDescriptor, this effectively means that caching instances of any model with a `CountryField` is going to destroy the cache (slow gets/sets, and fills up the cache very quickly).

Maybe that countries_object could be stored by some kind of reference rather than storing the entire object?

**Comment by SmileyChris** [comment]
Thanks for the tests and your prompting to fix this, @craigds -- can you see any problem with my method?

**Comment by craigds** [comment]
I'm a little confused, but maybe it's because pickle is really confusing. I presume the trick here is that [`return None`](https://github.com/SmileyChris/django-countries/commit/7286e68d7f413edca079dd8537e4a7d5427badb0#diff-c0dd2798d8e6d30e9666c11dc589a9edR33) which prevents serialisation of the countries _instance_, but the _class_ is serialised and preserved on load?

If so... nice work 👍 🚀
