### ISSUE TITLE
most recent locale .mo and .po files needed in repo

### ISSUE THREAD

**Issue by jayliew** [SmileyChris/django-countries#194]
Hi Chris,

I noticed that transifex shows that there are new translations, but the .mo and .po files in /locale/ hasn't been updated in 2-3 months. 

Are these changes that need to be transferred from transifex to the github repo?

That aside, the README doesn't include instructions on how to activate switch from one language to another.

Thanks!

**Comment by jayliew** [comment]
whoops - I found this: https://github.com/SmileyChris/django-countries/issues/158

So the relevant code snip is here, with the emphasis on _(name) :)

So I guess the last question is whether or not the most up-to-date .mo and .po files can be added to the github repo?

`country_select = models.CharField(
    verbose_name=_(u'In which country were you born?'),
    widget=widgets.Select(),
    choices=tuple((code, _(name)) for code, name in list(countries))  # notice the call to `_()` on name
)`

**Comment by SmileyChris** [comment]
The translation files are kept up to date. If they haven't been updated in 3 months then they haven't changed.

Activating a locale is explained in the Django docs.
