### ISSUE TITLE
Use flag-icon-css

### ISSUE THREAD

**Issue by llann** [SmileyChris/django-countries#196]
Hi, first thanks for django-countries :) Awsome tool!

About the flags, would be cool to include vectorial graphics instead of png, like including this lib: https://github.com/lipis/flag-icon-css

What do you think?

**Comment by SmileyChris** [comment]
Thanks, llann :) 

For an extra 7.8mb (that's SVGs, no other overhead) I'm not sure it is worth it. 
People can build the html class based on the country code and use that (or whatever they like) externally.

In fact, the individual flag images are only there for backwards compatibility now, people should use `.flag_css` and the sprite file (a whopping 22k for all flags in a single request).
