### ISSUE TITLE
value too long for type character varying(2) when running migrations with postgresql

### ISSUE THREAD

**Issue by allandereal** [SmileyChris/django-countries#198]
django.db.utils.DataError: value too long for type character varying(2)
This error arises while am running manage.py migrate on python3.5

**Comment by SmileyChris** [comment]
I need some more details. Is this your initial migrations when adding a country? Are you updating from a previous version of django-countries? Have you changed a CountryField to use multiple=True (or back again)?

**Comment by allandereal** [comment]
@SmileyChris , I figured out that if one makes migrations using sqlite db, they raise the error while trying to migrate them into postgresql db.
So what i did was to delete the migrations created from sqlite, and create new migrations using postgresql, and the error was gone. maybe, this is something you can look into?

**Comment by SmileyChris** [comment]
I'll take a look

**Comment by SmileyChris** [comment]
This seems more of an issue at an individual's project level rather than the django-countries project specifically. Not sure we have anything to fix here.

**Comment by saladgg** [comment]
> @SmileyChris , I figured out that if one makes migrations using sqlite db, they raise the error while trying to migrate them into postgresql db.
> So what i did was to delete the migrations created from sqlite, and create new migrations using postgresql, and the error was gone. maybe, this is something you can look into?

Thank you for this man, after dozen hours of struggle finally I have a  reason to call it a happy new year (2019)

**Comment by djjudas21** [comment]
@allandereal sorry to resurrect the zombie thread... what's the difference in the migration output between SQLite and Postgres? I do all my development on SQLite but someone has reported this when running my code in their Postgres environment. I don't have postgres to hand to re-make my migrations so I'm to just edit what I've got

**Comment by djjudas21** [comment]
Fixed it. I had to drop the `max_length=2` arg from my existing migrations (which were generated with django-countries 2.x!)

https://github.com/camerahub/camerahub/pull/845/commits/8958dceaf29e04199afd85d98de076a40b128c33
