### ISSUE TITLE
docs update

### ISSUE THREAD

**Issue by khashashin** [SmileyChris/django-countries#201]
I'm new to programming for django and the problem is exactly this. But nevertheless a small line can save a lot of time.
[I asked a question on Stackoverflow](https://stackoverflow.com/a/45695127/7986808) thx @gasman

**Comment by SmileyChris** [comment]
If you can think of a place to put it in the docs, please go ahead and create a pull request!

**Comment by khashashin** [comment]
Made some changes in the documentation
[pull request](https://github.com/SmileyChris/django-countries/pull/202)
