### ISSUE TITLE
Required Attribute Missing from CountrySelectWidget for Required CountryFields when COUNTRIES_FIRST_BREAK Setting Turned On

### ISSUE THREAD

**Issue by verngutz** [SmileyChris/django-countries#206]
When `blank=True` is not set on the `CountryField` of a model, the corresponding `CountrySelectWidget` in the `ModelForm` should render the `select` element with a `required` attribute.

Python version: 3.5.2
Django version: 1.11.4

**Comment by SmileyChris** [comment]
It does render it with a `required` element.

```python
In [1]: from django.forms import *

In [2]: from django_countries.tests.models import Person

In [3]: class F(ModelForm):
   ...:     class Meta:
   ...:         model = Person
   ...:         fields = ['country']
   ...:         

In [4]: f = F()

In [5]: f['country'].as_widget()[:50]
Out[5]: u'<select name="country" required id="id_country">\n '
```

**Comment by SmileyChris** [comment]
Oops, here's the proof with a `CountrySelectWidget` too:

```pyhon
In [7]: from django_countries.widgets import CountrySelectWidget

In [8]: class F(ModelForm):
   ...:     class Meta:
   ...:         model = Person
   ...:         fields = ['country']
   ...:         widgets = {'country': CountrySelectWidget()}
   ...:         

In [9]: f = F()

In [10]: f['country'].as_widget()[:50]
Out[10]: u'<select name="country" required onchange="var e=do'

```

**Comment by verngutz** [comment]
Hmm... I ran the exact same snippet and got a different output.

```python
# models.py
class Person(models.Model):
    country = CountryField()

# forms.py
class F(ModelForm):
    class Meta:
        model = Person
        fields = ['country']
        widgets = {'country': CountrySelectWidget()}
 
# shell
>>> f = F()
>>> f['country'].as_widget()[:50]
'<select name="country" id="id_country" onchange="v'
```

And oops, sorry, I forgot to specify earlier that I'm on Python 3.5.2 and Django 1.11.4.

**Comment by SmileyChris** [comment]
[Tests passing](https://travis-ci.org/SmileyChris/django-countries/builds/280598120) across the board. My guess is that you're actually running Django <1.10

**Comment by verngutz** [comment]
I'm running Django 1.11. I did a fresh install and started a new project, and the simple examples above do work correctly. So I tried investigating further what was going on with my old project. The culprit seems to be the `COUNTRIES_FIRST_BREAK` setting. With this set, the `required` attribute goes away.

**Comment by SmileyChris** [comment]
Right, I can see that if I add a test for `COUNTRIES_FIRST` and `COUNTRIES_FIRST_BREAK`. Specifically failing on 1.11 but not 1.10 interestingly -- maybe a regression?

**Comment by SmileyChris** [comment]
The [HTML5 spec](https://dev.w3.org/html5/spec-preview/the-select-element.html#placeholder-label-option) reads:
> If a select element has a required attribute specified, does not have a multiple attribute specified, and has a display size of 1; and if the value of the first option element in the select element's list of options (if any) is the empty string, and that option element's parent node is the select element (and not an optgroup element), then that option is the select element's placeholder label option.

> If a select element has a required attribute specified, does not have a multiple attribute specified, and has a display size of 1, then the select element must have a placeholder label option.

I kind of remember not allowing another blank option before countries first in this case to avoid another error (two blank options, both getting `selected="selected"`) but will have to investigate that again.

**Comment by verngutz** [comment]
The current behavior is that there is only one blank option, which gets move to after the end of the countries first options. I'm not sure if that violates the HTML5 spec, but I personally think it doesn't. 

Thanks for all the help, and for taking the time to investigate this!

**Comment by SmileyChris** [comment]
As per my quoted spec, it must explicitly be the first option element that is an empty string to be considered the select element's placeholder label option. Seems pedantic, but it's the spec.

In any case, this is Django core enforcing this, not django-countries so there isn't much we can do from this end (unless it was to explicitly bypass this restriction, which I'm not considering a valid form of action). If you want to do it yourself, you can add a `def use_required_attribute(self, initial):` which returns true on a subclass of the widget and use that explicitly.
