### ISSUE TITLE
CountryField raises ValidationError when assigned an alpha-3 country code.

### ISSUE THREAD

**Issue by Borkason** [SmileyChris/django-countries#209]
When running `full_clean()` on a model instance, the CountryField throws a ValidationError if I did assign a country using a ISO 3166-1 alpha-3 code, instead of an alpha-2 code, despite both codes being recognized.

```python
class Person(models.Model):
    country = CountryField()

>>> Person(country="FI").country.name  # 'FI' correctly recognised as 'Finland'
Finland
>>> Person(country="FI").full_clean()  # 'FI' correctly validated as 'Finland'
>>> Person(country="FIN").country.name  # 'FIN' correctly recognised as 'Finland'
Finland
>>> Person(country="FIN").full_clean()  # 'FI' wrongly validated as an invalid choice.
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\Borkason\Documents\python_stuff\venv\lib\site-packages\django\db\models\base.py", line 1249, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'country': ["Value 'FIN' is not a valid choice."]}
```

**Comment by Borkason** [comment]
Reason is that in the following loop, only alpha-2 codes are validates and no alpha-3 codes.

https://github.com/django/django/blob/4d60261b2a77460b4c127c3d832518b95e11a0ac/django/db/models/fields/__init__.py#L578-L592

**Comment by Borkason** [comment]
Is this patch included in version 5.0? I still have the same error.

**Comment by SmileyChris** [comment]
If you click on the commit link, you can see it's only in master. If you want to test against that and confirm it's working for you, that'd be helpful.

**Comment by Borkason** [comment]
Looks good on my end. Any plans when you push this to PyPI?

**Comment by SmileyChris** [comment]
5.1 released just now
