### ISSUE TITLE
Add nationalities feature

### ISSUE THREAD

**Issue by SmileyChris** [SmileyChris/django-countries#21]
Nationalities and contries are related but not exactly same. it would sound logic to have both.
(with a stateless entry)

---
- Bitbucket: https://bitbucket.org/smileychris/django-countries/issue/21
- Originally Reported By: [Christophe31](http://bitbucket.org/Christophe31)
- Originally Created At: 2012-08-20 18:15:37

**Comment by hendrikschneider** [comment]
Is it possible to reopen this issue?
