### ISSUE TITLE
Template tag for full list of countries

### ISSUE THREAD

**Issue by traVaulta** [SmileyChris/django-countries#211]
I can't seem to find a template tag for rendering a full list of countries in HTML - useful if used with DRF and some front-end javascript framework (that doesn't use Django forms or widgets rather it's own componentes). It's just a few lines of code but it would be cleaner if this was provided with this plugin:
`@register.assignment_tag`
`def get_countries():`
&nbsp;&nbsp;&nbsp;&nbsp;`"""Returns all countries in a list"""`
&nbsp;&nbsp;&nbsp;&nbsp;`return list(countries)`

**Comment by SmileyChris** [comment]
Sounds worthy. Want to try your hand at a pill request? Bonus points for tests 😉

**Comment by traVaulta** [comment]
Ok, thanks for the fast response 😃 , all done with tests -> PR created in fork.
