### ISSUE TITLE
required positional arguments: 'to' and 'on_delete' in Django 2.0.1

### ISSUE THREAD

**Issue by pwldp** [SmileyChris/django-countries#219]
Hi!
In Django 2.0.1, Python 3.5.2  I have an error:

country = models.ForeignKey()
TypeError: __init__() missing 2 required positional arguments: 'to' and 'on_delete'

Regards.

**Comment by SmileyChris** [comment]
Doesn't look like you're doing anything with django-countries here, you're just setting a field called country to a ForeignKey (which will require those arguments of course)
