### ISSUE TITLE
Basque locale missing compiled .mo file (@5.1) 

### ISSUE THREAD

**Issue by eillarra** [SmileyChris/django-countries#220]
Without the compiled file the translations cannot be loaded [[eu](https://github.com/SmileyChris/django-countries/tree/master/django_countries/locale/eu/LC_MESSAGES)] [[eu_ES](https://github.com/SmileyChris/django-countries/tree/master/django_countries/locale/eu_ES/LC_MESSAGES)].

**Comment by SmileyChris** [comment]
Whoops, fixed and released as v5.1.1

**Comment by eillarra** [comment]
Thanks!
