### ISSUE TITLE
Whether `null=True` is supported

### ISSUE THREAD

**Issue by vporton** [SmileyChris/django-countries#225]
Need to say in `README.rst` whether `null=True` is supported for countries.

**Comment by SmileyChris** [comment]
Documentation already states that the field is based on a CharField so the same logic applies. You can use a null=True, but you usually shouldn't.

**Comment by iMerica** [comment]
`null=True` doesn't work for me. I'm using `django-countries==5.3.2`

Response from Django Rest Framework:

`b'{"country_code":["This field may not be null."]}'`.

**Comment by iMerica** [comment]
Test cases:

- Literal null value  [FAIL]
- Empty string value (using null=True, blank=True) [FAIL]
- Omitting the field entirely from the payload: [PASS]
