### ISSUE TITLE
Feature: add (not selected) choice

### ISSUE THREAD

**Issue by vporton** [SmileyChris/django-countries#227]
Please add option to display something like (`(not selected)`) as the first choice of `LazyTypedChoiceField(choices=countries)`.

If it is possible with the current version, please explain how.

**Comment by SmileyChris** [comment]
As the docs say, use `blank_label` to label the choice. Set `blank=True` if you want the option to set the field back to blank for existing instances.

**Comment by vporton** [comment]
It does not work:

    country = LazyTypedChoiceField(choices=countries, blank_label='(select country)')

produces

    TypeError: __init__() got an unexpected keyword argument 'blank_label'

`blank=True` is also not accepted.

**Comment by SmileyChris** [comment]
Ooh, you're trying to use countries on a non-modelform with a blank option...

Probably the easiest way is to do:
```python
country = LazyTypedChoiceField(choices=CountryField().get_choices())
```
