### ISSUE TITLE
Allow to remove "required" attribute from CountrySelectWidget

### ISSUE THREAD

**Issue by vporton** [SmileyChris/django-countries#228]
It seems there is no way to make `CountrySelectWidget` for a `country = CountryField("Country", null=True)` model field without `required` HTML attribute.

**Comment by vporton** [comment]
`self.fields['country'].required = False` did the job.

**Comment by SmileyChris** [comment]
Probably adding blank=True to the CountryField  instead would the intended
effect.

**Comment by vporton** [comment]
Yes `blank=True` did the job.

But I had `null=True` in `CountryField`. It should have been enough.

So it is a bug (that it is required despite of `null=True`).

**Comment by SmileyChris** [comment]
Not a bug. As stated in the official Django documentation:
> For both string-based and non-string-based fields, you will also need to set blank=True if you wish to permit empty values in forms, as the null parameter only affects database storage (see blank).
