### ISSUE TITLE
Typo in Panama name (es locale)

### ISSUE THREAD

**Issue by ericdaniel** [SmileyChris/django-countries#233]
Panama ---> Panamá

https://github.com/SmileyChris/django-countries/blob/c2c0c7bd8ca2059a173ae15de31f664129008deb/django_countries/locale/es/LC_MESSAGES/django.po#L773

Thanks.

**Comment by SmileyChris** [comment]
Thanks, for the heads up. It needs to be fixed here: https://www.transifex.com/smileychris/django-countries/language/es/
