### ISSUE TITLE
Bootstrap or other formating parameters

### ISSUE THREAD

**Issue by born4web** [SmileyChris/django-countries#234]
Is there any way or you plan to implement passing formating parameters into widget from Bootstrap od other palform? Forms are unified and formated except the country TAG.

Something like:

widgets = { 'contry': CountrySelectWidget(attrs={'class': 'form-control'}),

Thanks Petr

**Comment by SmileyChris** [comment]
We're not doing anything different than standard Django widgets. That method (or changing the widget template on newer Django versions) should both work fine.
