### ISSUE TITLE
Further attributes to COUNTRIES_OVERRIDE beyond a Code and a Name

### ISSUE THREAD

**Issue by marksweb** [SmileyChris/django-countries#239]
I have a request from a client to add Kosovo (#25) to a list of available countries.

The site is primarily backed by the use of IOC codes and looks to display countries by their IOC value.

To support Kosovo as a custom country I've added the setting to django;

    COUNTRIES_OVERRIDE = {
        'XK': _('Kosovo'),
    }

I've not been able to find where this setting gets loaded, but obviously it creates `Country` objects with a `code` and `name`, but can further attributes (`ioc_code`) be added to these overrides?

**Comment by rwflick** [comment]
I have this same question. I need to limit the list and I read the docs for the COUNTRIES_OVERRIDE but I am not sure where and how to include this list.  Do you include it as a parameter for CountryField() in the model?  What if you are using a custom form?  How would you limit the country list in a custom form? Thanks!!
