### ISSUE TITLE
Any desire to add ISO 4217 code for currencies?

### ISSUE THREAD

**Issue by simkimsia** [SmileyChris/django-countries#240]

**Comment by anuj9196** [comment]
I also need this. Please add currency symbol as well to the list

**Comment by comradekingu** [comment]
@simkimsia Maybe https://hosted.weblate.org/projects/iso-codes/iso-4217/ (temporarily?) solves your problem

**Comment by SmileyChris** [comment]
You should be able to easily make a python app which uses the new [plugin system](https://pypi.org/project/django-countries/#country-object-external-plugins) to integrate with the `Country` object.
