### ISSUE TITLE
New translation for Afrikaans (af)

### ISSUE THREAD

**Issue by friedelwolff** [SmileyChris/django-countries#244]
I added a new translation for Afrikaans (af) on Transifex. I hope you can include it in the next release!

Thank you!

**Comment by friedelwolff** [comment]
@SmileyChris: I see you recently released version 5.3.3 and updated translations in commit d5e677ec. I don't see my new Afrikaans (af) translation from Transifex in the commit though :-(  Would it be possible to incorporate the translation in git and the next release?

Thank you!

**Comment by SmileyChris** [comment]
Pulled from transifex, I'll put out a release today
