### ISSUE TITLE
Add emojis?

### ISSUE THREAD

**Issue by eillarra** [SmileyChris/django-countries#249]
Emojis can be an interesting addition considering that they are more and more supported in mobile devices and that it will only require a simple data dictionary to implement it. We could just access it as another read_only property of the Country class: 'country.emoji'.

What do you think? An initial list could be generated from here:
<https://apps.timwhitlock.info/emoji/tables/iso3166>

**Comment by SmileyChris** [comment]
So something like the [`Country.unicode_flag`](https://github.com/SmileyChris/django-countries#the-country-object) option already there? 😉
