### ISSUE TITLE
Flag image for undefined / unset country

### ISSUE THREAD

**Issue by malexmave** [SmileyChris/django-countries#251]
In some situations, it may be desirable to display a flag that indicates that the country is unknown / not set. In my use case, I am crowd-sourcing (among other things) country information and would like to be able to indicate that the country for a specific item was not yet set (and thus needs someone to set it). The flag could also be automatically displayed in the dropdown country select list of the included form if the country is still blank.

Would it be possible to get a special flag for this (e.g. blank flag with questionmark), or do you strictly limit yourself to the flags of existing countries (in which case I'll come up with a homebrew solution)?

**Comment by SmileyChris** [comment]
I'm not sure any fallback flag will be "generic" enough for all cases. Probably best done as custom `if not country.flag` logic.
