### ISSUE TITLE
North Macedonia

### ISSUE THREAD

**Issue by batisteo** [SmileyChris/django-countries#254]
On Febuary 13th, the country name was oficially changed to **North Macedonia**.

It is now updated on the ISO website.

![Screenshot from 2019-03-22 16-21-31](https://user-images.githubusercontent.com/2727048/54833638-ca1e6e80-4cbe-11e9-965b-922c562d3b59.png)

**Comment by felix-engelmann** [comment]
will be fixed by PR #263

**Comment by zout** [comment]
Plz update, and merge #263 in, thank you very much, would save me some ugly code.
