### ISSUE TITLE
Fix in Portuguese & Brazilian translations

### ISSUE THREAD

**Issue by browniebroke** [SmileyChris/django-countries#255]
We found a few incorrect translations in European Portuguese & a few missing in Brazilian.

* [Macedonia](https://pt.wikipedia.org/wiki/Maced%C3%B4nia_(regi%C3%A3o)), corrected from "Macedônia" to "Macedónia" in pt_PT (although this should be changed to North Macedonia it seems #254)
* [Iran](https://pt.wikipedia.org/wiki/Ir%C3%A3o) corrected from "Irã" to "Irão" in pt_PT
* Missing translation for "Holy See", translated as "Santa Sé" in pt_BR

I've updated Transifex, is there anything I can do to help get them released?

**Comment by SmileyChris** [comment]
Transifex updated, pushing a release today...
