### ISSUE TITLE
TypeError when using multiple=True field in readonly admin

### ISSUE THREAD

**Issue by mvbrn** [SmileyChris/django-countries#265]
django-countries==5.3.3

Model has field CountryField(multiple=True). When ModelAdmin for this model is read only (has_change_permission method returns False) TypeError occurs:
<img width="717" alt="Screen Shot 2019-05-22 at 15 39 29" src="https://user-images.githubusercontent.com/21321875/58179126-d4052380-7ca7-11e9-93be-f7440bf15aab.png">

**Comment by SmileyChris** [comment]
I can't see an easy way around this... I could remove the `flatchoices` property of the field, but I'd have to look into where else Django expects to be able to use this.

This is low priority and for now I'd just say "you can't do that". If someone wants to look in to it more then feel free to open a new issue with possible options.
