### ISSUE TITLE
Same name for Serializer field and Model field may cause  unexpected keyword argument 'required'

### ISSUE THREAD

**Issue by phoebebright** [SmileyChris/django-countries#272]
In the serializer if you may have::

     from django_countries.serializer_fields import CountryField
     from .models import *

then the serializer ends up using the CountyField for the model instead of the serializer.  Of course specifying the models you want specifically, solves the problem.

    from .models import MyModel

In my case I had in the serializer::

      country = CountryField(required=False)

And this gave me the error::

      TypeError: __init__() got an unexpected keyword argument 'required'

Wanted to document this somewhere in case anyone else had this issue.

**Comment by SmileyChris** [comment]
Thanks, another example of why you should never `import *` ;)
