### ISSUE TITLE
Any thoughts on integrating country coordinates or bouding boxes?

### ISSUE THREAD

**Issue by binoyudayan** [SmileyChris/django-countries#274]
Hello 
I'm working on a django project with maps. It would be nice for me to get bounding boxes for each country with alpha2 or alpha3 codes. I'm  not sure about the broader perspective and usability of this feature to other users of django_countries. 

I have found some helpful data as follows
1. https://developers.google.com/public-data/docs/canonical/countries_csv
2. https://gist.github.com/graydon/11198540

I though of adding this data and into django_countries locally in my project and using it to make my life easy. Please share your thoughts on this.

**Comment by SmileyChris** [comment]
There have been a lot of requests for these kind of extensions in
django-countries. I think what would be good is to have it as a separate
project that could plug into django-countries core.
I would propose this:
```
setup(
    ...
    entry_points={'django_countries.Country': 'coords =
django_countries_coords.get_coords'},
    ...
)
```
which would dynamically add a new `Country.coords` property, calculated by
calling `get_coords` (passing it the `Country` instance).

How does that sound?

**Comment by SmileyChris** [comment]
Hopefully the [plugin system](https://pypi.org/project/django-countries/#country-object-external-plugins) makes it easier for you to integrate with the `Country` object.

**Comment by binoyudayan** [comment]
Sounds good. I'll try this.
Thank you :)
