### ISSUE TITLE
Django countries override setting problem

### ISSUE THREAD

**Issue by mischmid** [SmileyChris/django-countries#277]
Hey, I tried overriding the COUNTRIES_OVERRIDE settings, however my new custom countries do not seem to be properly handled by the library.

```
from django_countries import settings as dj_countries_settings

dj_countries_settings.COUNTRIES_OVERRIDE = {  # Add two custom countries to django_countries
    'EU': {'name': 'European Union', 'alpha3': 'EUN', 'numeric': 998}, 
    'GO': {'name': 'Global', 'alpha3': 'GLO', 'numeric': 999},
},
```
when displaying all countries, I get following output for my custom countries:

```
from django_countries import countries
for code,name in list(countries):
	print(code,name)
```

TF French Southern Territories
**EU GO**
GA Gabon
GM Gambia

and when I try to access the country dict over the defined key, I get the following output aswell:
![image](https://user-images.githubusercontent.com/18579898/65123518-b8125400-d9f3-11e9-99d9-cc24e91683aa.png)

what am I doing wrong?

**Comment by SmileyChris** [comment]
Don't override `django_countries.settings`, just put `COUNTRIES_OVERRIDE` in your project's settings module.
I found a bug with `COUNTRIES_OVERRIDE` complex dictionary format when you use `"name":` instead of a list of `"names":` and potentially that could be messing things up too? Try doing this for now: 
```python
COUNTRIES_OVERRIDE = {  # Add two custom countries to django_countries
    'EU': {'names': ['European Union'], 'alpha3': 'EUN', 'numeric': 998}, 
    'GO': {'names': ['Global'], 'alpha3': 'GLO', 'numeric': 999},
},
```

**Comment by mischmid** [comment]
I tried your suggestions, however I still get the same output...

```
from django_countries import countries
dict(countries)['EU']
'GO'
```

**Comment by mischmid** [comment]
@SmileyChris

**Comment by SmileyChris** [comment]
Ah, I see the error (and I duplicated it in my copy-paste):
You have a trailing comma when you define the dictionary:
```python
COUNTRIES_OVERRIDE = {  # Add two custom countries to django_countries
    'EU': {'names': ['European Union'], 'alpha3': 'EUN', 'numeric': 998}, 
    'GO': {'names': ['Global'], 'alpha3': 'GLO', 'numeric': 999},
}  # <--- you have a comma here, so COUNTRIES_OVERRIDE is really a tuple :P
```
