### ISSUE TITLE
Settings override isn't working in tests

### ISSUE THREAD

**Issue by therefromhere** [SmileyChris/django-countries#282]
It seems that `self.settings` isn't working correctly in the tests.

Eg in `TestCountrySelectWidget`, for tests using `with self.settings(COUNTRIES_ONLY={"AU": "Desert"}):` the rendered HTML still contains all countries.

Maybe something to do with non-lazy settings evaluation?

**Comment by therefromhere** [comment]
Moving the `modelform_factory()` call out of setup and inside the `with self.settings` scope seems to fix it, not sure why yet though.

**Comment by SmileyChris** [comment]
Fixed in 32b6273dc93f237e6da7bfcb8765f1d358db4152
