### ISSUE TITLE
Necessary to use CountryFieldMixin when using explicit CountryField?

### ISSUE THREAD

**Issue by gotexis** [SmileyChris/django-countries#288]
When I totally missed CountryFieldMixin and just used explicit CountryField(), on creation, I get the error that 'field is required ' when I totally supplied the field as {country: 'NZ'}.

The error is gone when I removed the field and just use the Mixin provided. So my question is, is it  absolutely necessary to use the mixin regardless?

**Comment by gotexis** [comment]
my bad... i total saw it after i dig further...

**Comment by gtljaymodi** [comment]
No. I'm using `CountryField()` and it takes `country:'NZ'` without any problems.

**Comment by SmileyChris** [comment]
CountryFieldMixin is only necessary on a ModelSerializer which is building the country fields based on the actual model field.
