### ISSUE TITLE
Taiwan official name is “Republic of China”

### ISSUE THREAD

**Issue by SmileyChris** [SmileyChris/django-countries#29]
According to [Wikipedia](http://en.wikipedia.org/w/index.php?title=Taiwan&oldid=546230830), the official name of Taiwan is “Republic of China”.

I fixed it on [my fork](/acatton/django-countries/overview), but it might have broken some translation.

---
- Bitbucket: https://bitbucket.org/smileychris/django-countries/issue/29
- Originally Reported By: [Antoine Catton](http://bitbucket.org/acatton)
- Originally Created At: 2013-03-29 18:11:32

**Comment by synotna** [comment]
ISO 3166-1 lists Taiwan as Taiwan, Province of China

With common names turned off, django-countries is Taiwan (Province of China)

:)

**Comment by SmileyChris** [comment]
Go to https://www.iso.org/obp/ui/#search and search for "tw" and you'll see the parenthesis are correct.

**Comment by synotna** [comment]
Apologies as commented in the other ticket, falsely assumed Wikipedia's ISO entries would match!
