### ISSUE TITLE
force_text() deprecated with Django 3

### ISSUE THREAD

**Issue by MonsieurV** [SmileyChris/django-countries#290]
Hello,

`force_text()` [has been deprecated](https://docs.djangoproject.com/en/3.0/releases/3.0/#features-deprecated-in-3-0) in Django 3.

Thus we have warning using django-countries with Django 3:
```
lib/python3.6/site-packages/django_countries/__init__.py:252: RemovedInDjango40Warning: force_text() is deprecated in favor of force_str().
    code = force_text(code).upper()
```

Could we make the switch to `force_str()`?

I could provide a PR if necessary :)

**Comment by Mogost** [comment]
Also
```
/site-packages/django_countries/data.py:34: RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
```

**Comment by hugorodgerbrown** [comment]
The PR for this is a bit more complex than expected as the library supports versions back to Django 1.8 and Python 2.7. Supporting versions across the Python 3 cut-off is awkward.

**Comment by MonsieurV** [comment]
Considering Django 3.0 only [supports Python 3.6+](https://docs.djangoproject.com/en/3.0/releases/3.0/#python-compatibility), maybe the solution is to do a new major release for django-countries that will only - at least officially - support Python 3 (and more recent Django versions, like 2.1 or 2.2)?
This wouldn't prevent from making bug, security fixes and minor evolution of the django-countries version 5 for users still using older Django versions or Python 2.

Maybe the new release could be based on #287, with @Djailla work to only supports Python 3.5+.

Because supporting so different versions of Django (and Python) will indeed become very difficult or cumbersome.

**Comment by washeck** [comment]
Both Python 2 and Django 1.11 will be supported only until April 2020 so there is no need to keep the compatibility for more then 3 month from now.

**Comment by SmileyChris** [comment]
Fixed on master

**Comment by sweetpythoncode** [comment]
When its be released to **PYPI**?
