### ISSUE TITLE
Database design decision for multiple countries

### ISSUE THREAD

**Issue by saiprashanth173** [SmileyChris/django-countries#292]
Hi folks, 

Thanks for developing Django Countries

We are part of the database group at Georgia Tech. We are developing a tool, called sqlcheck, for assisting database application developers in designing performant and maintainable applications. sqlcheck automatically detects sub-optimal database design choices and suggests better alternatives. For instance, storing comma-separated values in a column violates the first normal form, which impacts the performance, maintainability, and extensibility of the application.

In your application, we observe the usage of comma-separated values for the multiple countries option. Our experiments with sqlcheck showed that there is a significant performance impact in querying or updating such columns and could also lead to returning of inaccurate records. The alternate better approach, i.e., having an intermediate table to represent this Many to Many relationship, could result in an approximately 10x performance gain and also makes sure that the application is maintainable, accurate and extensible. Could you please share the rationale behind this design decision?

We hope that sqlcheck will assist the broader community of database application developers with designing applications. Your feedback will be greatly appreciated.

Thanks for your time.

**Comment by SmileyChris** [comment]
Django countries allows for custom countries to be added in settings, so this would add in a burden to keep the m2m list in sync. The multiple countries field is definitely suboptimal from a performance perspective -- I wouldn't recommend it for consumption on sites with high loads, but there are easy workarounds like manually doing m2m relationships that use the standard non-multiple countries fields.

**Comment by saiprashanth173** [comment]
Thank you for letting us know.
