### ISSUE TITLE
Sizeable memory leakage due to PyUCA collator

### ISSUE THREAD

**Issue by interDist** [SmileyChris/django-countries#296]
On our website we have a search functionality which returns objects (models), one of the fields of which is a `Country`. We constantly have memory problems and what I observed recently is that every single search increases the memory usage by a couple MB's. I discovered (by the help of __pdb__ and __objgraph__) that the `pyuca.trie.Node` objects are not being released: 

![Usage of objects over time in django_countries module](https://user-images.githubusercontent.com/1909012/75333568-a2e4ff80-5886-11ea-93f3-0bfca849980e.png)

This seems to be related to the Collator being defined as a global object.

**Comment by SmileyChris** [comment]
Thanks for your work here. Merged and (finally) released as v6.0
