### ISSUE TITLE
readonly CountryField error

### ISSUE THREAD

**Issue by srublev** [SmileyChris/django-countries#298]
Looks like `CountryField` with `multiple=True` is not compatible with Django Admin read only field setting

Got the following error:
`Exception Value: unhashable type: 'list'`
`Exception Location: <...>\lib\site-packages\django\contrib\admin\utils.py in display_for_field, line 382`

I have the following code:
```
from django.db import models
from django_countries.fields import CountryField

class Person(models.Model):
    originates = CountryField(multiple=True, blank=True)
```
```
@admin.register(Person)
class PersonAdmin(admin.ModelAdmin):
        def has_change_permission(self, request, obj=None):
            return False

**Comment by vkosh** [comment]
I ran into the same issue. Unfortunately there's no way yet to tell django how to display reaonly fields (see the similar issue https://github.com/SmileyChris/django-countries/issues/265). I workarounded the issue by adding string property to the model and replacing 'countries' field with the property name in get_fields of the in admin model.
E.g.

```python
class Person(models.Model):
    originates = CountryField(multiple=True, blank=True)

    @property
    def originates_str(self):
        return ', '.join([c.code for c in self.originates])

@admin.register(Person)
class PersonAdmin(admin.ModelAdmin):
    def has_change_permission(self, request, obj=None):
        return False

    def get_fields(self, request, obj=None):
        fields = super().get_fields(request, obj)
        if not self.has_change_permission(request):
            try:
                index = fields.index('originates')
                fields[index] = 'originates_str'
            except ValueError:
                pass
        return fields
```

**Comment by SmileyChris** [comment]
Not easily fixed and there's a suitable workaround.

**Comment by mathias4github** [comment]
Getting the same issue, the workaround is not working for me. My model ist not using any ReadOnly Fields. 

destination = CountryField(default='DE', multiple=True)


```
Request Method: | GET
-- | --
/admin/products/shippingproduct/
3.0.8
TypeError
unhashable type: 'list'
/mpc/env/lib/python3.7/site-packages/django/contrib/admin/utils.py in display_for_field, line 382
```

Sees to be a problem here: 

`

Variable | Value
-- | --
_boolean_icon | <function _boolean_icon at 0x7ff8cb481510>
empty_value_display | '-'
field | <django_countries.fields.CountryField: destination>
value | [Country(code='DE')]

`
