### ISSUE TITLE
Installation issues with 6.0 & 6.1 (egg fragments, "metadata for project name unknown")

### ISSUE THREAD

**Issue by goetzb** [SmileyChris/django-countries#302]
I've just tried to update the `django-countries` package on an **AWS Elastic Beanstalk Python 3.6** environment **from 5.5 to 6.1** and noticed that the **deployment would fail**. I then tried again with 5.5 and it worked fine, then with 6.0 and it failed. It seems to be an **installation issue** with the Python package.

It looks like **some packaging meta data might be broken** in the releases 6.0 and 6.1 - or at least some configuration data causes problems with deployments on AWS Elastic Beanstalk with Python 3.6 (maybe it's an Amazon Linux or Python 3.6 issue - **it works fine on my local Python 3.6 on MacOS**).

In the list of **installed packages**, `django-countries` isn't included, but **`unknown-0.0.0`**.

The relevant log output is:
```log
Collecting django-countries==6.1 (from -r /opt/python/ondeck/app/requirements[...])
    Downloading https://files.pythonhosted.org/packages/cd/08/2ec975194d51c3648465ecd1239d870bfe20de4146626a3c3e5f12074e11/django-countries-6.1.tar.gz (619kB)
    Running setup.py (path:/tmp/pip-build-uejmevas/django-countries/setup.py) egg_info for package django-countries produced metadata for project name unknown. Fix your #egg=django-countries fragments.
```

Since in the `pip` output says **"produced metadata for project name unknown. Fix your #egg=django-countries fragments."**, I thought it might be a packaging issue. Looking quickly at the configuration and the package files on PyPi, I couldn't see what might be the problem - but I also have no experience with creating Python packages.

Maybe the issue occurred because for 5.5 there is a Wheel available on PyPi and for 6.0 and 6.1 there isn't? 
* https://pypi.org/project/django-countries/5.5/#files
* https://pypi.org/project/django-countries/6.0/#files

Please let me know if you need any further details to investigate this issue.

**Comment by SmileyChris** [comment]
Just checked and the `PKG-INFO` file has the correct project name, so not sure why this is an issue. The lack of wheels was due to the Python 3 switch -- zest releaser stopped building up those due to the removal of the `[bdist_wheel]` section of the `setup.cfg`.

Fixed for next release, and to fix the current situation I just built and pushed the 6.1 wheel:
https://pypi.org/project/django-countries/6.1/#files
