### ISSUE TITLE
Django Rest Framework serializer_fields ViewSet?

### ISSUE THREAD

**Issue by irwanOyong** [SmileyChris/django-countries#303]
Hi, thank you for the greatwork.
I am trying to use your library for building a REST API containing the country list. 

`from django_countries.serializer_fields import CountryField

class CountrySerializer(serializers.Serializer):
    country = CountryField()`

But I am wondering on how should I write the ViewSet and router part? For read-only and CRUD in React.
Thank you.

**Comment by SmileyChris** [comment]
This isn't really an issue with django-countries, use the drf forums or #django on irc to get help.
