### ISSUE TITLE
CountryField null instead of empty string

### ISSUE THREAD

**Issue by bplociennik** [SmileyChris/django-countries#309]
I would like to ask about return empty string instead of a null value for `to_representatin` if we don't have `code`. There is some reason for doing this in that way? I think return null value would be easier for people working on API.

```
class CountryField(serializers.ChoiceField):
    def to_representation(self, obj):
        code = self.countries.alpha2(obj)
        if not code:
            return ""
        if not self.country_dict:
            return code
        return {"code": code, "name": force_str(self.countries.name(obj))}
```

**Comment by SmileyChris** [comment]
Not sure it's worth introducing this slight backwards incompatibility.
