### ISSUE TITLE
Error with use country_dict in 'drf' and 'drf-yasg'

### ISSUE THREAD

**Issue by sweetpythoncode** [SmileyChris/django-countries#312]
```
    raise AssertionError("[format, enum, pattern] can only be applied to primitive " + str(_obj_type))
AssertionError: [format, enum, pattern] can only be applied to primitive <class 'drf_yasg.openapi.Schema'>

```
I think **to_representation** should be refactored to return a string when using **country_dict**

**Comment by SmileyChris** [comment]
`to_representation` is being used to return a dictionary, and works without yasg. Maybe a different base class should be used, or some extra config to avoid the schema documentation failing.

Happy to reopen if more details can be provided, or even better, a PR :)
