### ISSUE TITLE
Kosovo (XK) Missing?

### ISSUE THREAD

**Issue by tufelkinder** [SmileyChris/django-countries#314]
Is there a reason why Kosovo, country code XK, is excluded from the django countries list?

**Comment by pakal** [comment]
Hello, we got bitten as well by this  ^^

**Comment by SmileyChris** [comment]
As #5, it's because it is not an ISO listed country.

You can add it yourself by adding the following to your settings:
```python
from django.utils.translation import gettext_lazy as _

COUNTRIES_OVERRIDE = {
    "XK": {"name": _("Kosovo"), "ioc_code": "KOS"},
}
```

**Comment by shawnngtq** [comment]
@SmileyChris , by settings, you mean `settings.py`? Just want to make sure it's the cleanest method 😁

**Comment by SmileyChris** [comment]
Yes, your projects settings module. And yes there's a flag: https://github.com/SmileyChris/django-countries/blob/ae3a4c21535aec04f424d8788ea9ce2071809726/CHANGES.rst#613-18-august-2020

**Comment by shawnngtq** [comment]
Got it, thanks for building this library, it's really awesome 👍
