### ISSUE TITLE
Documentation: How to update an instance of an object by appending a new country 

### ISSUE THREAD

**Issue by eburmicz** [SmileyChris/django-countries#315]
Hi,

Thank you for this project, it looks very useful.  I don't understand why this project doesn't use a database backend though - it is limiting the way that I use standard Django to update a many-to-one relationship on countries. I basically want to append a new country to the list of countries already associated with an instance but this appears to be tricky given that the country is stored as a string.

Could you indicate how we are supposed to go about this? Should this sort of syntax be added to the docs?

Ed

**Comment by eburmicz** [comment]
I should add that it is an ingestion script so not a form.

**Comment by SmileyChris** [comment]
It's not that tricky, and explained here: https://github.com/SmileyChris/django-countries#customize-the-country-list
