### ISSUE TITLE
Getting countries by continent

### ISSUE THREAD

**Issue by crukundo** [SmileyChris/django-countries#317]
I am aware about the customisations we can make with this app but curious whether it's possible to add a filter where you specify a continent(s).

**Comment by SmileyChris** [comment]
Not opposed to the idea. If someone wants to start a PR it'd have more chance of getting in ;)

**Comment by SmileyChris** [comment]
Isn't something that's being actively developed or that there have been much interest in. I'm going to close this as a non-active issue.
