### ISSUE TITLE
multiple=True and a "worldwide" entry?

### ISSUE THREAD

**Issue by jedie** [SmileyChris/django-countries#320]
What is the best practice to provide multiple countries select able and a "worldwide" option?

The current solution that i used is to add a separate `worldwide = models.BooleanField()` flag.

But it would be cool to combine this into `CountryField()`

**Comment by SmileyChris** [comment]
If "Worldwide" should be a separate option, independent of (and in addition to) individual countries, then you could just make a custom `COUNTRIES_OVERRIDE` setting (or `override` attribute of a custom Countries object as discussed in "Single field customization") and provide a custom `"XX": _("Worldwide")` country?
