### ISSUE TITLE
Extremely slow admin when displaying country in list_display

### ISSUE THREAD

**Issue by maestrofjp** [SmileyChris/django-countries#321]
Using country as a list_display field in the admin is 10x slower than not.  My example admin below shows the issue with the slow time -- the admin is only showing 10 objs per page.  Using a custom `display_name` to show the 2 character country code instead fixes the issue.

This is with debug True, but the same problem exists when debug is False. No sure where to start to fix this issue.

```python
@admin.register(Retailer)
class RetailerAdmin(admin.ModelAdmin):
    list_display = (
        'id',
        'is_active',
        'company_name',
        'country',
    )
    
    def display_country(self, obj):
        return str(obj.country)
```

Using `display_country` instead of `country`:
![No Country](https://user-images.githubusercontent.com/1403999/99883559-e5f1ba80-2bed-11eb-8e5a-557e5ac3d4dc.png)

Using `country`:
![With Country](https://user-images.githubusercontent.com/1403999/99883561-e68a5100-2bed-11eb-82a4-fc8d58c8c3ce.png)

**Comment by Mogost** [comment]
>No sure where to start to fix this issue.

I would suggest starting with profiling.
There is line profiling extension for django debug toolbar that may be helpful
https://pypi.org/project/django-debug-toolbar-line-profiling/

**Comment by peterfarrell** [comment]
@Mogost It's definitely somewhere in the render area of converting the 2 character code to a human readable name and this exists in separate applications in both Django 2.2 and 3.1.  At first, I thought it might be related to the use of i18n however I have been able to reproduce it in an app without i18n.

**Comment by SmileyChris** [comment]
This is a weird one, I'm surprised that it's an issue that no one has mentioned before if it is just some general bug... 
Are you using pyuca?

**Comment by maestrofjp** [comment]
@SmileyChris Yes, we are using pyuca so countries sort correctly for languages other than English.

**Comment by SmileyChris** [comment]
Think I noticed the tests being slower on the pyuca runs, hence why I
asked... I wonder if it's that slowing it down.

Could you try testing without pyuca installed and see if that speeds things
up at all? Should probably be a setting for the use of that, really

**Comment by SmileyChris** [comment]
Right, that should fix it. Can you please install the current github master branch and confirm this fixes it for you?

**Comment by maestrofjp** [comment]
@SmileyChris

Using Django-Countries 6.2.1 using country field in admin:
1. 17,010ms
1. 16,967ms
1. 15,997ms

Using Django-Countries master:
1. 1,775ms
1. 1,585ms
1. 1,683ms

Looks way better. I noticed similar issues in an application that did not use PyUCA and it looks way better there too.
