### ISSUE TITLE
Change default attribute used when calling str() on CountryField

### ISSUE THREAD

**Issue by qcoumes** [SmileyChris/django-countries#324]
Is there any easy way to change the attribute used when calling `str()` on a `CountryField`?

I noticed a `str_attr` kwarg on `Country`, but is there any way to define it from a `CountryField`?

**Comment by qcoumes** [comment]
If there is no way to currently achieve this, I can probably work on a PR.

**Comment by SmileyChris** [comment]
No way, but should be easy to add. Have a go at the PR. I'd say `countries_str_attr` to match the current `countries_flag_url` kwarg.

**Comment by SmileyChris** [comment]
Implemented in 4d74583ce21e7a08fa4db0008ce63430002d70da

**Comment by qcoumes** [comment]
Just so I can plan things on my side, do you know when you plan to release `7.1` ?
