### ISSUE TITLE
Scotland, England and Wales are missing from country fields

### ISSUE THREAD

**Issue by ZhivkoZaikov** [SmileyChris/django-countries#326]
Scotland, England, Northern Ireland and Wales are missing from country fields, instead there is United Kingdom only. But I have to specify the exact country and its country code.

**Comment by SmileyChris** [comment]
The default country list matches iso 3166-1. You can customize this list
yourself:
https://pypi.org/project/django-countries/#customize-the-country-list

It does bring up an interesting point that the default length is only 2
chars when it may make sense to allow customizing the length to accommodate
iso 3166-2 five (or six including the dash) character codes.

**Comment by llombard** [comment]
indeed the followinf code doesn't work:

````
COUNTRIES_OVERRIDE = {
    'GB': None,
    'GB-ENG': _("England"),
    'GB-NIR': _("Northern Ireland"),
    'GB-SCT': _("Scotland"),
    'GB-WLS': _("Wales"),
}
````
because of this:

> django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:
> ERRORS:
> mymodel.pays: (fields.E009) 'max_length' is too small to fit the longest value in 'choices' (6 characters).

Thanks for fixing this if possible.
Laurent

**Comment by SmileyChris** [comment]
Yep, the current assumption is that all countries fit in the 2 character space. It shouldn't be hard to calculate the minimum required length by looking at max length of all the overridden countries list (and do a similar check for the total length when using multiple=True too)
