### ISSUE TITLE
Widget compatibility with generic views

### ISSUE THREAD

**Issue by Turosik** [SmileyChris/django-countries#332]
Hello!
I'm using django generic views and CountryField is working fine until I'm trying to apply CountrySelectWidget. Is it some kind of incompatibility with generic views or I'm doing something wrong? Take a look please...

```
# models.py
class Organisation(models.Model):
    ...
    country = CountryField(blank=True, verbose_name='Страна', blank_label='(выберите страну)')

# views.py
class OrganisationProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = Organisation
    fields = ['tin', 'short_name', 'full_name', 'entity_number', 'country', 'logo']

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['country'].widget = CountrySelectWidget()
        return form

# organisation_update.html
    ...
    <table>
        {{ form.as_table|localize }}
    </table>
    ...
```

If the country was previously selected (without widget) I can see that country flag in the field after applying the widget but drop down of select field is empty. And if country was not selected than field is just empty and drop down is empty.
I've been looking at stackoverflow and some other resources but found nothing about compatibility with generic views...

Please help!

**Comment by SmileyChris** [comment]
I think this is because you're instanciating the widget after the fact, so it'll have no choices defined. You could use a Form class that sets `Meta.widgets` or you could pass the choices into the widget explicitly, something like: 
```
form.fields['country'].widget = CountrySelectWidget(choices=form.fields['country'].choices)
```
