### ISSUE TITLE
Add pyuca to the requirements

### ISSUE THREAD

**Issue by adamsol** [SmileyChris/django-countries#335]
Currently, `pyuca` is listed in readme as an optional package "for more accurate sorting of translated country names". Unfortunately, this makes it quite difficult to find why `pyuca` is installed with an application if no comment has been left. I was ready to remove `pyuca` from my application's requirements, and only after some digging in the repository have I found that it's used here (and it matters for my language).

A better solution would be to install the package automatically with `django-countries`. This way it will show as required in `pip show pyuca`.

I guess that `pyuca` is not used by default due to performance reasons (#330). If this is the case, then a configuration variable (e.g. `COUNTRIES_UNICODE_COLLATION`, just like `COUNTRIES_FIRST`) would be a good solution.

**Comment by SmileyChris** [comment]
On the other hand, always having the package install when you don't need it though is a bit "bloaty". The correct solution is to add it as an optional extra, then recommend installing like `pip install django-countries[pyuca]` if required.

Care to throw that together as a pull request?

**Comment by adamsol** [comment]
You're right, an optional dependency is probably a better idea if the package is not to be used in most cases. It seems that with this solution `pyuca` still won't be displayed as required by `django-countries` in `pip show pyuca`, but at least it will be clear in the requirements what it is used for.

I've created a PR: #337.
