### ISSUE TITLE
Taiwan, Hongkong and Macau are not countries.

### ISSUE THREAD

**Issue by chenyulue** [SmileyChris/django-countries#342]
In the CountryField, it's not appropriate to list Taiwan, Hongkong and Macau as countries. Taiwan, Hongkong and Macau are a part of China, not countries. If you want to make a distinction among Taiwan, Hongkong, Macau and the mainland of China, I suggest replacing Taiwan, Hongkong and Macau  with Taiwan China, Hongkong China and Macau China respectively.

Thanks!

**Comment by SmileyChris** [comment]
Hi @chenyulue - Django Countries follows country names provided by ISO 3166-1, but additionally defaults to the more "common names" of some of these countries as of this commit: e64eca162beef87ff4f4b9e79a72d9af1854fe5b
It looks like an oversight that this COUNTRIES_COMMON_NAME isn't documented in the primary README.

**Comment by SmileyChris** [comment]
Now documented here: https://github.com/SmileyChris/django-countries/blob/master/README.rst#customize-the-country-list
