### ISSUE TITLE
COUNTRIES_FIRST_BREAK renders as "True" in admin interface

### ISSUE THREAD

**Issue by phihag** [SmileyChris/django-countries#351]
In a project with the django setting `COUNTRIES_FIRST_BREAK` set to True, I have a model with a `CountryField`:

```
class MyModel(django.db.models.Model):
    countries = CountryField(multiple=True, blank=True)

@admin.register(MyModel)
class MyModelAdmin(django.contrib.admin.ModelAdmin):
    fields = ['countries']
```

This renders as:

![image](https://user-images.githubusercontent.com/779568/123382468-46851380-d592-11eb-85cc-5533d94ada74.png)

How can I render the break as a true break and not as the string `True`? I tried adding a widget with
```
def formfield_for_dbfield(self, db_field, **kwargs):
    if db_field.name == 'countries':
        kwargs['widget'] = CountrySelectWidget
    return super().formfield_for_dbfield(db_field, **kwargs)
```

but that is even more broken, not even showing a multi select:
![image](https://user-images.githubusercontent.com/779568/123382655-7a603900-d592-11eb-83ab-26ca392f5a8f.png)

**Comment by SmileyChris** [comment]
`COUNTRIES_FIRST_BREAK` is supposed to be a string (it's the label between the `COUNTRIES_FIRST` list and the rest of the countries), not a boolean value.

**Comment by phihag** [comment]
Thanks! Setting
```
COUNTRIES_FIRST_BREAK = '──────────'
```
produces a decent line. It's still user-selectable, but ok.

![image](https://user-images.githubusercontent.com/779568/123742229-9a05a300-d8ab-11eb-8b9f-c2f376cabe85.png)
