### ISSUE TITLE
Multiple countries selected filter not working

### ISSUE THREAD

**Issue by iamharshkumar** [SmileyChris/django-countries#361]
I have Company object which have India and Iceland countries selected but when I filter with Company.objects.filter(country="IN") then I got an empty array If I select only one single country for the company then filter is working fine but not with multiple countries select

**Comment by SmileyChris** [comment]
All multiple does is comma separate the selected countries. Try
`country__contains="IN"`.

**Comment by iamharshkumar** [comment]
Thanks it is working :)
