### ISSUE TITLE
Blank=True is not working?

### ISSUE THREAD

**Issue by hungtienvu** [SmileyChris/django-countries#362]
My custom form field

`   country = CountryField(blank_label="Select country", blank=True).formfield()`

![image](https://user-images.githubusercontent.com/2724285/147374788-9637caaa-fc97-4faa-af41-b5b4d2c246a1.png)

![image](https://user-images.githubusercontent.com/2724285/147374795-20525385-095b-4570-a5f5-a58728329d06.png)

**Comment by SmileyChris** [comment]
Sounds like something wrong with your custom form field then. I added in a test to show that the standard select field isn't getting `required`
