### ISSUE TITLE
Common names are not always honored for non-english translations

### ISSUE THREAD

**Issue by cfra** [SmileyChris/django-countries#364]
When we are translating a country name into a non-English language, the shorter name from `COMMON_NAMES` is not always honored:

```python
>>> from django.utils import translation
>>> from django_countries import countries
>>> countries.name('VE')
'Venezuela'
>>> translation.activate('de')
>>> countries.name('VE')
'Venezuela (Bolivarische Republik)'   # Expected value: "Venezuela"
```

This seems to be caused by commit https://github.com/SmileyChris/django-countries/commit/eee10e68fac207867ce08b74ba1700ad2d1ca6ff

Note that this only happens, because the German translation of the English common name "Venezuela" is also "Venezuela", so the condition in https://github.com/SmileyChris/django-countries/blob/62ed634f2e96ea734416c07f4034f4f37b13e706/django_countries/__init__.py#L246 holds true, and we start to compare fallback names.

For cases where the German translation of the English common name is different, e.g. "Russland" vs "Russia", translation of the name works just fine, because the condition in line 246 doesn't hold true:

```python
>>> from django.utils import translation
>>> from django_countries import countries
>>> countries.name('RU')
'Russia'
>>> translation.activate('de')
>>> countries.name('RU')
'Russland' # With the bug, we would see "Russische Föderation" here
```
I am not sure what the intention of the statement in line 246 is.

Is it testing whether a translated version of the common name is available?

If yes, it seems like testing the translated string for equality with the original string is not the correct approach for this.

**Comment by SmileyChris** [comment]
Yes, the idea was that if translations didn't yet provide the common name, it could fallback to the full translated name.

There doesn't seem to be an easy and reliable way to check if a string is actually translated or if it's falling back to the default locale...

Should probably just drop this fallback check.
