### ISSUE TITLE
Include demonyms

### ISSUE THREAD

**Issue by voidus** [SmileyChris/django-countries#365]
It would be nice if the Country object could provide demonyms such as "Polish" or "Ghanan".

Quick google search turned up a few data sets of uncertain quality, and including it in the application could be non-trivial.

Besides that, translation could also be a significant effort.

**Comment by SmileyChris** [comment]
This is why external plugins is a feature. A potential nice to have, but not something that needs to live in core:
https://github.com/SmileyChris/django-countries#country-object-external-plugins

**Comment by voidus** [comment]
Oh, yes, thanks for your answer and sorry that I missed it!
