### ISSUE TITLE
Can't use country_dict with DRF

### ISSUE THREAD

**Issue by forrestkouakou** [SmileyChris/django-countries#373]
It's weird but I still struggling with the `country_dict` parameter. I still can't use it with DRF
Error: `Error occurred during checks: TypeError("__init__() got an unexpected keyword argument 'country_dict'")
`
Django version 4.0.2
DRF 3.13.1
Python 3.8.10

**Comment by SmileyChris** [comment]
are you sure you're importing the DRF country field?
```python
from django_countries.serializer_fields import CountryField
```
You can see clearly it's handling the country_dict argument: https://github.com/SmileyChris/django-countries/blob/master/django_countries/serializer_fields.py#L9
