### ISSUE TITLE
serious performance regression in v7.3.0 / v7.3.1

### ISSUE THREAD

**Issue by jgb** [SmileyChris/django-countries#376]
Hello,

I haven't narrowed it down yet where exactly this is coming from within django-countries, but when I upgrade from v7.2.1 to v7.3.1 some of my views that use django-countries go from needing 3 seconds to load to needing 32 seconds.
Downgrading django-countries back to v7.2.1 fixes the performance regression.

Greetings,

jgb

**Comment by SmileyChris** [comment]
Well that doesn't sound pleasant. Could you try a quick `git bisect` to try and see which commit was the offending one?

**Comment by SmileyChris** [comment]
Found it, and releasing a fix now.
