### ISSUE TITLE
label seems to be missing for CountryField()

### ISSUE THREAD

**Issue by shailensobhee** [SmileyChris/django-countries#380]
I am using CountryField directly in a form. 

```
class BookForm(forms.Form):
    your_phone_number = forms.CharField(label=_('Your phone number'))
    your_country = CountryField(blank_label=(_('Select country'))).formfield()
```

In the above, in my rendered form in the template, I have control on the label text 'Your Phone number'. I cannot find a way to make the same work for CountryField, as there is no such label parameter it accepts.

**Comment by SmileyChris** [comment]
```python
CountryField(blank_label=(_('Select country'))).formfield(label='Your country')
```
?
