### ISSUE TITLE
Further type hints

### ISSUE THREAD

**Issue by adamchainz** [SmileyChris/django-countries#393]
I'm rolling out Mypy's strict mode on a project, and the type hints in django-countries are triggering some errors. Specifically from activating the [`disallow_untyped_calls` flag](https://mypy.readthedocs.io/en/stable/config_file.html#confval-disallow_untyped_calls), which requires typed contexts only call typed functions, triggering errors like:

```
example/core/models.py:112: error: Call to untyped function "CountryField" in typed context  [no-untyped-call]
```

This is because, whilst django-countries has a `py.typed` file, `CountryField.__init__` is not fully type hinted - the same for the other hints.

Would you be interested in a PR that enables strict mode within django-countries' Mypy env, and expands the type hints?

**Comment by SmileyChris** [comment]
Yes, a PR that expands type hints to allow for mypy's stricter mode would be welcome.

**Comment by SmileyChris** [comment]
Let's close this for now. Good job on your commits to django-stubs :)
