### ISSUE TITLE
Cannot set Default country

### ISSUE THREAD

**Issue by sharad740** [SmileyChris/django-countries#400]
##### In forms.py
```
from django_countries.widgets import CountrySelectWidget
from django import forms 
from enroll.models import Person

class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ('name', 'country')
        widgets = {'country': CountrySelectWidget()}
```

Returns : Select Country by default

#### In models.py
```
from django.db import models
from django_countries.fields import CountryField

class Person(models.Model):
    name = models.CharField(max_length=100,)
    country = CountryField(blank_label='(select country)',blank=True)
    
    def __str__(self):
        return self.name

```

**Comment by SmileyChris** [comment]
Setting a default on the CountryField removes the blank choice. 

See `favourite_country` example here:
https://github.com/SmileyChris/django-countries/blob/9d433adb7d552c22359fb4496777404df5a7a35b/django_countries/tests/models.py#L7-L14
Tested here:
https://github.com/SmileyChris/django-countries/blob/9d433adb7d552c22359fb4496777404df5a7a35b/django_countries/tests/test_fields.py#L622-L626
