### ISSUE TITLE
AttributeError: module 'django.utils.translation.trans_null' has no attribute 'catalog'

### ISSUE THREAD

**Issue by ktl-1** [SmileyChris/django-countries#401]
Python version 3.10.2
Django version 4.1.2
django-countries version: 7.4.1

Traceback:

> django_countries\__init__.py, line 58, in no_translation_fallback 
> django_countries\__init__.py, line 285, in translate_pair
> django_countries\widgets.py, line 29, in get_choices

Exception occurs when making use of `country = CountryField(blank_label="Country").formfield()`.

**Comment by clashthe** [comment]
Python version 3.9
same bug

**Comment by clashthe** [comment]
reverted back to 7.3.2
everything is ok

**Comment by SmileyChris** [comment]
Should be fixed in 7.4.2, just released
