### ISSUE TITLE
Country names are automatically translated, I just want it to appear in English.

### ISSUE THREAD

**Issue by cnr91** [SmileyChris/django-countries#406]
Hi,

Country names are automatically translated into Turkish.

How can I prevent this?  I just want it to appear in English.

![image](https://user-images.githubusercontent.com/75105673/203705444-5188a95c-77d8-4d0c-96c0-a5ed3c6fa211.png)

**Comment by SmileyChris** [comment]
Probably the best way to handle this would be to [switch the language in your template](https://docs.djangoproject.com/en/4.1/topics/i18n/translation/#switching-language-in-templates) (using the standard `language` template tag).
