### ISSUE TITLE
ModuleNotFoundError: asgiref

### ISSUE THREAD

**Issue by za** [SmileyChris/django-countries#408]
Hi there, I am getting this ERROR when using version 7.5

```
/django_countries-7.5-py3.8.egg/django_countries/__init__.py", line 22, in <module>
    from asgiref.local import Local
ModuleNotFoundError: No module named 'asgiref'
```

**Comment by SmileyChris** [comment]
While that may be the case, you may just be able to install asgiref
manually to get it working...

**Comment by za** [comment]
Hmmm I could try that.

BTW, should we put requirement of the Django version somewhere? 

I am closing this issue now.
