### ISSUE TITLE
Slow admin loading

### ISSUE THREAD

**Issue by luke3141** [SmileyChris/django-countries#41]
I have a field of type CountryField. In the admin interface, when I use this field in the list display, it's incredibly slow to load when there are ~100 rows.

I've tried `using list_select_related = ('country',)`, or even `list_select_related = True`, but there is no speedup (DDT doesn't report any extra queries with or without this - 5 in each case). However, there is significant speed increase when I use a filter (reducing the number of rows) or if I remove this field from the list display interface.

Is there any way to speed this up/cache the results?

**Comment by ronny-rentner** [comment]
It's 10 years later and I have unfortunately the same problem. Showing a country column in admin makes it 10 times slower than without, so an admin change list view takes 700 ms CPU time instead of 70 ms according to django-debug-toolbar.

I am using django-countries version 7.6.1.
