### ISSUE TITLE
Andorra hard to find in Spanish translation

### ISSUE THREAD

**Issue by MacLake** [SmileyChris/django-countries#412]
I just got an issue from a user that Andorra was not in the selection list of countries. In fact it is there, but in the Spanish version of our website you can’t find it where you expect it, i. e. under Andorra, as it’s [translated as Principado de Andorra](https://github.com/SmileyChris/django-countries/blob/master/django_countries/locale/es/LC_MESSAGES/django.po#L132). I suggest to change it to “Andorra”.

**Comment by MacLake** [comment]
I have made the necessary [changes](https://github.com/SmileyChris/django-countries/compare/master...MacLake:django-countries:master) to improve this issue. I will have it checked by a Spanish native speaker before I create a pull request.

**Comment by SmileyChris** [comment]
Those all definitely sound like good changes (keeping the primary country name first, then the details afterwards - to match the English translations).

You should make these changes on [transifex](https://www.transifex.com/projects/p/django-countries/) and they'll be automatically pulled in on the next release.
