### ISSUE TITLE
multiple=True  widget + limit

### ISSUE THREAD

**Issue by michaelhjulskov** [SmileyChris/django-countries#421]
Hi,

Is it possible for me to use another widget for multiple ?

Would be very cool if we could choose other widgets to select multiple countries.
widget_type='std_dropdown'
widget_type='std_dropdown_with_checkboxes'
widget_type='two_coloumn_dropdowns'
etc.

I would also like to limit how many countries is allowed to select. 
max_limit=5
default should be unlimited

Thank you :)

**Comment by SmileyChris** [comment]
You should be able to use a custom widget, you just have to extend the mixins that django-countries provides (look into the code and you should see how we're doing it).

You could also limit how many countries can be selected, but you'd do that as a model validator, not as something that needs to be changed in this codebase.
