### ISSUE TITLE
Adding Kosovo

### ISSUE THREAD

**Issue by uberfresh** [SmileyChris/django-countries#423]
Hi,

Can you add Kosovo, please? I really need that.

Thanks :smile:

**Comment by dream-guide** [comment]
Hi, 

I had the same issue you can add the following in your settings:
`COUNTRIES_OVERRIDE = {
    'XK': {
        'names': ['Kosovo'],
        'alpha3': 'XXK',
        'ioc_code': 'KOS',
    },
}
`
The flag file should be located here:
static/your_project/img/country-flags/xk.svg

![xk](https://github.com/SmileyChris/django-countries/assets/65447929/08b722b3-52fe-4881-9002-584e2152ba34)

**Comment by brammittendorff** [comment]
Same problem here !

**Comment by tomdtp** [comment]
push

**Comment by dream-guide** [comment]
> push
Kosovo is not in the ISO 3166-1 country code list that is probably why it's not included. 
You can add it manually (see code above).

**Comment by SmileyChris** [comment]
Yep, if it's not in ISO 3166-1 then it's not going to be included. Add it manually as above 👍🏻
