### ISSUE TITLE
Turkey localization key

### ISSUE THREAD

**Issue by ivanbat1** [SmileyChris/django-countries#426]
Hi!
Please update country localizations key in [this line](https://github.com/SmileyChris/django-countries/blob/main/django_countries/data.py#L263)

**Comment by SmileyChris** [comment]
Why? That's the iso name of turkey now

**Comment by volkantash** [comment]
Wrong. It is written as "Turkey" in English. We will painfully understand how wrong it was to force people to print "Türkiye" instead of "Turkey" in the recent past. It should remain "Turkey".

English: Turkey
Turkish: Türkiye

Don't change...

**Comment by SmileyChris** [comment]
It's changing, since that's the official ISO name.
