### ISSUE TITLE
DeprecationWarning: pkg_resources is deprecated as an API

### ISSUE THREAD

**Issue by raratiru** [SmileyChris/django-countries#439]
https://github.com/SmileyChris/django-countries/blob/48f17b45c76cda200bc2621e09a7dc4babdaa32f/django_countries/fields.py#L5

The above line causes the `DeprecationWarning`. 

According to [setuptools docs:](https://setuptools.pypa.io/en/latest/pkg_resources.html)

> Attention
> 
> Use of pkg_resources is deprecated in favor of [importlib.resources](https://docs.python.org/3.11/library/importlib.resources.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3.11/library/importlib.metadata.html#module-importlib.metadata) and their backports ([importlib_resources](https://pypi.org/project/importlib_resources), [importlib_metadata](https://pypi.org/project/importlib_metadata)). Some useful APIs are also provided by [packaging](https://pypi.org/project/packaging) (e.g. requirements and version parsing). Users should refrain from new usage of pkg_resources and should work to port to importlib-based solutions.

**Comment by SmileyChris** [comment]
Fixed in 7.6
