### ISSUE TITLE
Consider moving to jazzband

### ISSUE THREAD

**Issue by claudep** [SmileyChris/django-countries#444]
Hi @SmileyChris,

Several important patches are waiting to be reviewed/merged, and I suspect you may be overloaded in your available time for this project. What would you think about the idea of moving your package to the Jazzband team? It would be easier for others to help in reviewing, merging and releasing.

**Comment by washeck** [comment]
@claudep Do you know what is needed to transfer this package under Jazzband? I am considering to create a fork of django-countries, given that @SmileyChris is not responding to community (though I very much appreciate the work he's done so far) but so far I've only provided some patches to opensource projects and I'm not really sure if I should take the responsibility of maintaining such a fork  myself.

**Comment by stinovlas** [comment]
If transferred to jazzband, I'd be willing to invest some time and at least review and merge the pending merge requests

@washeck: You can find the conditions on https://jazzband.co/about/guidelines
All the main points are checked (viability, documentation, tests). The others (like adding `CONTRIBUTING.rst`) should be fairly easy to complete.

**Comment by SmileyChris** [comment]
I've definitely been overloaded and slacking on supporting my open source packages in the last year. I'm trying to get on top of it, so will retain ownership for now. **But** if you're interested in being a maintainer, then I'm more than willing to add some people to keep traction going :)
