### ISSUE TITLE
Ülke adlarını iki dilde görmek / Seeing country names in two languages

### ISSUE THREAD

**Issue by volkantash** [SmileyChris/django-countries#448]
Selamun aleyküm.

Ülke adlarını seçer iken ayarlardan belirlediğimiz dil ile seçebiliyoruz ancak bir yandan da ülkelerin adlarını o ülkelerin dillerinde görmeliyiz. Böylece kullanıcı hangisini biliyor ise onunla seçimini yapabilir. Örnek vereyim:

> Selamun aleykum.
>
> While selecting the country names, we can choose them in the language we specify from the settings, but on the other hand, we must also see the names of the countries in the languages of those countries. Thus, the user can make his choice with whatever he knows. Let me give an example:

- England | England
- Germany | Deutschland
- Turkey | Türkiye
- Saudi Arabia | السعودية

**Comment by SmileyChris** [comment]
This is an interesting translation issue. You could do this in django by changing the language back and forth because everything's a translatable string. I'm not sure exactly where in django-country core you'd put this...

Unless we have a more concrete suggestion as to how this should behave, i'll close this for now

**Comment by volkantash** [comment]
Gerçek kişiler ülke adlarını seçtiği dilde bilmiyor olabilir. Bu yüzden ülke adlarının o ülkenin resmi diline göre yanında da belirtilmesi erişebilirliği kolaylaştırır. Mevcut durumda bırakılması ise kişiyi bu dilde bu ülkenin adı ne acaba diye araştırmaya itiyor.

Bu aşağıdaki gibi kurulmalıdır:

seçilen dildeki adı | kendi dillerindeki adı

Örnek:

Benim dilim Türkçe ise

    İngiltere | England
    Almanya | Deutschland
    Türkiye | Türkiye
    Suudi Arabistan | السعودية

Benim dilim İngilizce ise

    England | England
    Germany | Deutschland
    Turkey | Türkiye
    Saudi Arabia | السعودية

Benim dilim Almanca ise

    Großbritannien | England
    Deutschland | Deutschland
    Türkei | Türkiye
    Saudi-Arabien | السعودية

>Natural persons may not know the country names in their chosen language. Therefore, stating country names according to the official language of that country facilitates accessibility. Leaving it in its current state forces one to search for the name of this country in this language.
>
>This should be set up as follows:
>
>name in selected language | name in their own language

>Example:
>
>If my language is Turkish
>
>     England | england
>     Germany | Deutschland
>     Türkiye | Türkiye
>     Saudi Arabia | السعودية
>
>If my language is English
> 
>      England | england
>      Germany | Deutschland
>      Turkey | Türkiye
>      Saudi Arabia | السعودية
> 
> My language is German
> 
>      Grossbritannien | england
>      Deutschland | Deutschland
>      Turkei | Türkiye
>      Saudi-Arabian | 

السعودية
