### ISSUE TITLE
Issue with Country Name

### ISSUE THREAD

**Issue by Princeprem76** [SmileyChris/django-countries#462]
The Country name for "NP" is provided Nepali but it should be Nepal. Same for "IN" it should be India not Indian.

**Comment by SmileyChris** [comment]
The english versions of these are fine. Maybe this is a problem in a specific translation?
https://github.com/SmileyChris/django-countries/blob/main/django_countries/data.py#L139
https://github.com/SmileyChris/django-countries/blob/main/django_countries/data.py#L191
