### ISSUE TITLE
Is there a simple way to have a model linked to many countries?

### ISSUE THREAD

**Issue by LeMeteore** [SmileyChris/django-countries#92]
Any advices on how to have a many to many relastionship with a Country?

**Comment by SmileyChris** [comment]
Hrm, there's no simple way at the moment. I'd probably suggest a simple model just containing a CountryField as a pk (and nothing else). Then just use a standard M2M field pointing to this one.

This isn't going to give you a nice single widget to control it with though. Maybe in the long term future (or if someone feels very motivated) a new custom field could be added to handle this.

**Comment by LeMeteore** [comment]
I see, thanks a lot.
