### ISSUE TITLE
Option to Suppress Flag from CountrySelectWidget

### ISSUE THREAD

**Issue by mmangione** [SmileyChris/django-countries#97]
Hello. I want your list of countries in a select field in my Django form, but I do not want the <img> tag with the flag in it. Can you add a boolean to suppress that rendered tag? Right now, I am doing that with Javascript.

**Comment by SmileyChris** [comment]
Maybe just don't use the `CountrySelectWidget` then?

**Comment by mmangione** [comment]
I would use the flag, but without control of where it is rendered, it doesn't fit well in the form. Perhaps another option would be to be able to pass in an id which the form would use to render the flag. Then, I could create my own img tag, place it and the widget would simply amend the values of my preplaced tag.

**Comment by SmileyChris** [comment]
So that's the real issue here -- controlling where the flag is rendered (otherwise like I said before, you could just not use the widget because it'd be a normal select otherwise).

There should be a class for the image class at the very least. Probably better if we used an `__init__` kwarg which used string formatting to handle the formatting. Something like this (with `layout` showing what the new default would be):
```
widget=CountrySelectWidget(layout='{widget}<img class="country-select-flag" style="margin: 6px 4px; position: absolute;" src="{flag_url}">')
```

**Comment by SmileyChris** [comment]
Am I correct in my assessment about what you really want here?

**Comment by mmangione** [comment]
Yep that is exactly what I was looking for. This will make this widget so much more useful!

**Comment by SmileyChris** [comment]
Try out master and see if that scratches your itch :)

**Comment by mmangione** [comment]
Yep. That works great!

**Comment by johntovor** [comment]
I have found a much simpler way to hide the flag.
I inspected the code in the console and noticed the country flag image has a class called "country-select-flag" so I just used CSS to hide it.

.country-select-flag {
       display: none;
}

This is what performed the trick for me.
