### ISSUE TITLE
Different country choices for different model fields

### ISSUE THREAD

**Issue by soult** [SmileyChris/django-countries#98]
For a website I need to limit the country choices on a per-field basis. The usual way of using the `COUNTRIES_ONLY` setting does not work here.

Example: A phone provider that has customers in the US and Canada, and allows calls to US, Canada and also the UK wants to log all calls:
```python
class Call(models.Model):
    customer = models.ForeignKey(Customer)
    calling_from = CountryField(choices=[
        ("US", _("United States of America")), ("CA", _("Canada"))]
    calling_to = CountryField(choices=[
        ("US", _("United States of America")), ("CA", _("Canada")),
        ("UK", _("United Kingdom and Northern Ireland"))]
```

Unfortunately this also doesn't work, because the choices kwarg [is always overwritten with the full list of countries](https://github.com/SmileyChris/django-countries/blob/master/django_countries/fields.py#L147-150).

Do you think that only setting the choices kwarg when it is unset would be ok or is there some other code that depends on it?

**Comment by SmileyChris** [comment]
As I was doing an update recently, this problem crossed my mind actually...
I have a working fix I'm just writing some tests for

**Comment by SmileyChris** [comment]
Have you had a chance to try out master yet, @soult ?

**Comment by soult** [comment]
Thank you for the quick change to the django-countries library. I am already using the updated version for my project.

Unfortunately this change will "break" migrations. Django will always think that the field has changed and create a new migration.

Example models.py:
```python
from django.db import models
from django_countries import Countries
from django_countries.fields import CountryField

call_countries = Countries(only=(("CA", "Canada"), ("US", "United States of America")))

class CallLog(models.Model):

    country = CountryField(countries=call_countries)

```

When writing a migration, all fields get deconstructed, then serialized, where iterables get converted to tuples (see [django.db.migrations.writer.py](https://github.com/django/django/blob/1.7.5/django/db/migrations/writer.py#L381-L392)), so the field is stored like this:
```python
('country', django_countries.fields.CountryField(max_length=2, countries=(('CA', 'Canada'), ('US', 'United States of America'))))
```

But the current version, which makemigrations compares it to, is this:
```python
('django_countries.fields.CountryField', [], {'max_length': 2, 'countries': <django_countries.Countries object at 0xdeadbeef>})
```

One way to fix this problem is to make CountryField also accept an iterable as countries kwarg and then convert it to a Countries instance, as can be seen in soult/django-countries@04c699576e4b779bc96ebd16a148b4737afc7a46, though I am not sure if this is the best way to tackle this problem.

**Comment by SmileyChris** [comment]
Hrm, I think the best way may be to add a `deconstruct` method and steal some of the logic from https://github.com/django/django/blob/1.7.5/django/db/migrations/writer.py#L352-L380 to reference the instance itself.

**Comment by SmileyChris** [comment]
Or even simpler, maybe you should just have to pass the `Countries` subclass, not an instance of it.

**Comment by SmileyChris** [comment]
On a slightly related not, I just pushed a commit to master so you can just have `COUNTRIES_ONLY = ['CA', 'US']`

**Comment by SmileyChris** [comment]
Ok, let's try this instead :)

**Comment by soult** [comment]
Works great, thanks!
