### ISSUE TITLE
Macedonia COMMON_NAME not translated in ja

### ISSUE THREAD

**Issue by almond55** [SmileyChris/django-countries#99]
The ja locale of django.po is missing Macedonia, which is listed in the COMMON_NAME in data.py. Supposed to be at line 36 but it skipped to Russia.

**Comment by SmileyChris** [comment]
Thanks! I hadn't uploaded the latest source language messages to transifex.

You can translate it here:
https://www.transifex.com/projects/p/django-countries/translate/#ja/djangopo?translated=no

**Comment by OmarIthawi** [comment]
@SmileyChris I've got your message on Transifex and translated Mecdonia.

Could you please update the source and release a new version so I can install it using `$ pip`?

Thanks,

**Comment by SmileyChris** [comment]
Thanks Omar. I'll wait a few days for the other translations to come in.

**Comment by almond55** [comment]
Thanks for putting it in the po file. Here's the ja translation for Macedonia: マケドニア

**Comment by OmarIthawi** [comment]
Hi @SmileyChris, Could you please release a new version? Thanks a lot :)

**Comment by SmileyChris** [comment]
3.3 is out, thanks for the reminder!

**Comment by OmarIthawi** [comment]
Thanks a lot Chris :)
